### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#10]
See https://github.com/mozilla/network-pulse/issues/251

**Comment by xmatthewx** [comment]
Any updates on this? Progress, blockers, or concerns?

**Comment by alanmoo** [comment]
The only thing we're tracking on the back end for now is favorites, as per @pomax's comments [here](https://github.com/mozilla/network-pulse/issues/251#issuecomment-273901850). I'm going to close this for now and we can open another issue when we have more specific requirements in the future.
