### ISSUE TITLE
optimize ordering of creators

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#109]
If an entry has multiple Creators, they seem to be listed based on the ID of a creator. As a result, the display favors old rather than new creators. Mozilla for example, will be listed before the name of a new fellow on their project, giving out credit backwards.  

In an ideal world, authors could choose that we list creators, putting primary people first, followed by smaller contributors. 

In a pretty good world, we would emphasize new creators, so that Mozilla and other frequent support orgs aren't listed before people a bunch times throughout the platform for their supporting role.

**Comment by xmatthewx** [comment]
This is not a critical bug, but a thing we should try and fix as we roll this out to a broader audience. cc @Pomax

**Comment by Pomax** [comment]
rather than "fix" I would say this is a thing we need to before anything try to define in terms of rigid rules, because content on the web is almost never by "Mozilla" but by individuals affiliated with Mozilla. What in-entry, or in-entry-dataset properties can we tap into to determine the prioritisation of creators?

**Comment by xmatthewx** [comment]
We want to capture the order that people list things in their form. Serve them up in the same order, trusting their attribution. On the admin side, we'd want similar control to correct/enhance entries.

That will not be trivial to implement. Let's do an interim fix because the current implement presents the exact opposite of what anyone will want and it will definitely be noticed as we show this to a growing list of people in the next couple of weeks.

**Comment by Pomax** [comment]
Just so I understand you correctly, is this what you're thinking?

1. User creates an entry, adds creators; first creator is "Carol", second is "Alice", third is "Bob".
2. User submits entry, entry is saved into the db
3. Pulse client application retries the entry, and sees a `creators` list that is ordered as "carol, alice, bob"
4. entry is presented in the client with the creators ordered as received.

**Comment by Pomax** [comment]
If so, it sounds like http://stackoverflow.com/questions/9602217/define-an-order-for-manytomanyfield-with-django (first answer is pretty detailed, second non-code answer http://stackoverflow.com/a/9602890 is more the hint what to look up in the django docs) implies this actually might be trivial, where we store an ordering value when entries come in.

**Comment by xmatthewx** [comment]
Yes, that's correct. Intuitive for a user who doesn't know about the underlying models. And...

Wow, this quickly gets complicated. Glancing through [the docs](https://docs.djangoproject.com/en/dev/topics/db/models/#intermediary-manytomany), makes me wonder: Does this create a ton of overhead? Are we introducing complexity that will bite us later? For example, will we lose the ability to offer auto-complete in the future?

**Comment by alanmoo** [comment]
Now that autocomplete has been implemented for tags, can we use the same technique for creators? And would that allow us to preserve order more easily?

**Comment by xmatthewx** [comment]
Auto complete would definitely help with consistency 👍. Let's file a ticket! Ordering will be a separate thing. We'll an entry will need to store the order of IDs, rather than relying on a table that simply relates a creator to a project.

**Comment by xmatthewx** [comment]
Does our tags autocomplete handle ordering? If so, awesome.

**Comment by Pomax** [comment]
I'm not sure... @alanmoo?

**Comment by alanmoo** [comment]
Turns out no. Also turns out new tags aren't being created (at least on staging). So, filing a ticket about that.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
