### ISSUE TITLE
Allow POSTing multiple entries at once

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#11]
Should the `/entries/` endpoint allow an array of entry objects posted to it, for the purposes of our initial data migration? Is there any other reason to do that, or a better way to migrate?

**Comment by Pomax** [comment]
it feels like we wrote a sufficient solution for this, do we need to do more or can we close this?

**Comment by alanmoo** [comment]
Yup, this is addressed in the `migraitons.html` file in the repo.
