### ISSUE TITLE
Refine auth and user roles

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#110]
We currently only have two levels of user:

- base user (no flags set) - simply having an account grants this user posting rights
- is_staff -  unquestioned full control over all the things including database hackery

We should extend user roles with a few more flags:

- base user (no flags set): known user account, but no posting rights
- trusted: has a user account, can submit entries.
- staff: is, literally, staff. Staff is automatically trusted (can we assume all `@mozilla` accounts are staff due to LDAP rules around revoking people who leave moz?).
- admin: can edit data on the site, including submitted content, but **cannot** change `is_admin` or `is_staff` flags on user records. Admins are automatically trusted but are not necessarily staff.
- superadmin: full, unfettered access to all the things.

Getting through the sign-in process for new users should automatically grant the "trusted" level of access. Making the distinction between base users and trusted users means we can flip a posting switch on spam accounts rather than deleting user accounts (deleting instead of revoking privileges would just let a spammer sign right back up).

This more refined user model also means we can open up Auth to "any gmail login", where we can mark plain logins as "trusted" without any staff privileges, and any login with a mozilla address as staff with the associated editing rights on the backend.

This still keeps pulse tied to gmail authentication, but we could then also start allowing alternative means of login that are granted `trusted` on signup (e.g. first sign in, really).

Thoughts @xmatthewx @alanmoo, @wex?

**Comment by xmatthewx** [comment]
related to: 
 - ldap discussion in pulse repo https://github.com/mozilla/network-pulse/issues/474#issuecomment-293031958
 - moderation https://github.com/mozilla/network-pulse/issues/438

**Comment by alanmoo** [comment]
This makes a lot of sense to me!

**Comment by xmatthewx** [comment]
This looks good. 
 - So a user can have multiple flags (`staff`, `admin`), rather than a single role? Cool. Nice a flexible. 
 - Seems like this model works both for Pulse and the Net Site, which is good. 

Trusted:
 - Can we call this group `Author`? Seems like ambiguous and I've been using Trusted with stakeholders to describe members we can onboard without moderation.
 - In the future, they should be able to edit/archive their own entries. Not a feature we need to build now, just thinking ahead.

**Comment by Pomax** [comment]
"what they can do" is more a question of which user group users are part of, so if I can refine this a little, changing the "trusted" to a better term: it's really mostly there to make a distinction between "has account, can't do things" and "has account, can do things" without saying a whole lot about what those things are, so the important part in any concrete implementation is that we have a flag that is "true" for one of those, and "false" for the other:

- "active" flag set vs nothing set (active allowed to do things, inactive not allowed to do things)
- trusted" flag set vs nothing set
- nothing set vs. "banned" flag set
- nothing set vs. "locked" flag set
- etc.

etc. I'm not a fan of "active" vs "inactive" because that's terminology generally understood to be about user login frequency, not permissions in the system.  I probably like a "locked" flag best here.

Django has a user group concept that we've not been making use of so far, but would be a good idea to start actually using here because it simplifies some of the work around user administration:

### roles set on individual users
- "superuser" flag to mark individuals as being full system administrators (this is required mostly because Django's base model makes this distinction, and the django `manage createsuperuser` command hooks into this)

### group policies
- locked: these users are effectively banned. They can log in, but whatever rights they might have are null and void. Even if they're in other groups as well
- staff, admin: same as above, just controlled through group policy rather than user policy
- ...and then more groups...

The third entry here represents any role that we come up with either now or in the future that should apply to "groups of users" rather than individuals, covering things like "Authors", "Editors" etc.

**Comment by xmatthewx** [comment]
Permissions via Group policies seem like a good approach. Locked is nice and unambiguous. 

`Member` – Default. Can create entries for pulse
`Author` – Can create content for website
`Moderator`  – Can moderate entries on pulse
`Editor` – Can edit/publish content created by others

**Comment by Pomax** [comment]
@alanmoo @xmatthewx given the fact that this is something we'll get "for free" when pulse-api is part of network-api, do we want to keep this issue open?
