### ISSUE TITLE
Enable CORS or jsonp

### ISSUE THREAD

**Issue by acabunoc** [mozilla/network-pulse-api#111]
I'm trying to embed the search results for featured projects in the global sprint site (static, hosted on github pages)
https://api.mozillapulse.org/entries/?format=json&search=mozsprint+2017

To do this, I need either CORS or jsonp responses enabled. As a workaround, I can commit the json in the repo and manually update whenever we have a new project.

thanks for your help!

**Comment by xmatthewx** [comment]
Any thoughts @Pomax @alanmoo @cadecairos ?

**Comment by alanmoo** [comment]
I think we might just need to add an env variable?

**Comment by acabunoc** [comment]
@alanmoo yes: https://mozilla.github.io/global-sprint

**Comment by cadecairos** [comment]
lets never use jsonp :)

enabling cors for this resource on the domain it will be requested from, using an env var, is fine

**Comment by alanmoo** [comment]
I added the env var, so it should just work? Dyno might need a restart but I'm not sure. On Monday, let me know if that did the trick @acabunoc?

**Comment by acabunoc** [comment]
Just tried it out! CORS not working -- can we restart the dyno? @alanmoo

**Comment by acabunoc** [comment]
Works great! Thanks @alanmoo 

https://mozilla.github.io/global-sprint/projects/

🎉
