### ISSUE TITLE
add RSS/Atom feeds

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#112]
Django has RSS and Atom feed capabilities built in. It would be wise for us to create feeds for the `latest` and `featured` routes by reading through https://docs.djangoproject.com/en/1.11/ref/contrib/syndication/#publishing-atom-and-rss-feeds-in-tandem and simply doing what they tell us to do =)

**Comment by xmatthewx** [comment]
wise words 😄
