### ISSUE TITLE
Convert tags to lowercase in submission

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#115]
Tags are currently stored as case-sensitive, yielding duplicate entries in the DB. Example: DIY and diy.

**Comment by Pomax** [comment]
counter argument: acronyms typically need to be capitalised, so having duplicates *should* be fine as long as case is ignored while searching for entries so that you find hits for "diy", "DIY", "Diy" etc alike?

**Comment by xmatthewx** [comment]
Hmmm. Complicated. Those are good points. Counter counter argument: We suffer on the analytics side trying to track trends on Mozfest, mozfest, and MozFest. 

I guess if we land a good autocomplete experience, we'll minimize unintentional differences. 

I will bump this to the backlog for now.

**Comment by mmmavis** [comment]
maybe what we are missing here is some GA tips from Arliss? 😉

**Comment by xmatthewx** [comment]
Actually. Hmmm. URLs aren't case sensitive. Our search isn't case sensitive. Probably doesn't impact analytics. The DBs difference will only matter if/when we start using the frequency of tags for ordering, suggestions, etc.  

Let's see what happens after we have autocomplete.

**Comment by Pomax** [comment]
URLs are most definitely case sensitive. Route handlers can be told to be smart about what to do with an incoming request, but https://www.mozillapulse.org/featured and https://www.mozillapulse.org/FEATURED for instance are two *different* URLs, that yield the same resource when requested from the server.

**Comment by Pomax** [comment]
closing due to this apparently not having been a true issue for over 2 years now ;)
