### ISSUE TITLE
copy the pulse-api database over to the network-api

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#116]
In order to finalise migration from the "pulse-api as its own database" to being house in the network-api project, we need to migrate the data from the pulse-api into the network-api. This will require migrations.

**Comment by cadecairos** [comment]
With the routes at `/api/pulse/*`, we won't need this because the existing Cloudfront behaviours will apply correctly.

**Comment by Pomax** [comment]
The current database as used by network-pulse-api is a different DB than the one running for network-api, so we still need a data migration, and because the network pulse user model is now a user profile instead, schema changes make things a little more complicated

**Comment by cadecairos** [comment]
Sorry, I thought this was a completely different bug

**Comment by Pomax** [comment]
we will not be doing this any time soon anymore.
