### ISSUE TITLE
Improve moderation

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#117]
Let's discuss the low-hanging fruit that's available to improve moderation next sprint.

**Comment by xmatthewx** [comment]
Moderation states: https://github.com/mozilla/network-pulse/issues/522
Moderation front-end: https://github.com/mozilla/network-pulse/issues/541

Others?

**Comment by Pomax** [comment]
It might also be necessary to have some UI provisions in the admin interface on the API side, in case bulk operations need to be performed and we don't want to work so close to the bare metal that we're writing SQL queries to get the job done.

**Comment by alanmoo** [comment]
Closing this as it's served its purpose. Design discussion is leading to an implementation ticket.
