### ISSUE TITLE
Add flake8 linting

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#127]
Even if you don't like PEP8 syntax, it's good to stick with them, and it's even better to have tooling in place that forces you to fix things when you don't use it... and for some reason flake8 won't run.

**Comment by mmmavis** [comment]
This has probably been fixed: https://github.com/mozilla/network-pulse-api/pull/179 /cc @Pomax

**Comment by Pomax** [comment]
In part - the repo now has the files set up for flake8 linting, but the README does not mention this yet, and it would be great if `manage test` also kicked off a flake8 run.

**Comment by Pomax** [comment]
closing.
