### ISSUE TITLE
rename "Creator" to "Author"

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#13]
Based on https://github.com/mozilla/network-pulse/issues/257#issuecomment-271641837 we will need to rename our `Creator` model to `Author` (and rename corresponding props/funcs)

**Comment by kristinashu** [comment]
Just double checking:
- person who is logged in and is adding the post to Pulse is called "author"
- the form field where an author says who worked on the project is called "creator" (and there could be multiple creators)

**Comment by Pomax** [comment]
Wait, that is very different from what Alan and I were asking in the above mentioned issue. The problem there was that while the person posting the entry is a clearly defined role, there were *three* roles that all collapsed into the "creator" noun (creator, contributor, partner) at the time of submission, which needed to be a single noun instead.

**Comment by kristinashu** [comment]
What are you calling the user submitting a post to Pulse?

**Comment by Pomax** [comment]
in the model that is the `Entry.published_by` field, which user facing would be shown in a way similar to what the redpen (Either literally "posted by ..." or a variant that has the same meaning to browsing users: just the user that posted to Pulse, not necessarily the user who made the content that entry talks about)

**Comment by Pomax** [comment]
Based on https://github.com/mozilla/network-pulse/issues/257#issuecomment-271937040, the proposed solution does not require a backend change, so we can close this issue.
