### ISSUE TITLE
Update users/views.py with the new redirect_uri

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#132]
Update this line https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/users/views.py#L44 with the new redirect_uri http://test.example.com:8000/api/pulse/oauth2callback

**Comment by Pomax** [comment]
This shouldn't actually be done, instead that line should fall back to "nothing", with the `sample.env` updated to reflect the new callback URL

**Comment by Pomax** [comment]
README.md and sample.env have been updated with the correct URI.
