### ISSUE TITLE
split EmailUser into a user and a userprofile model

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#133]
This will make it much more easy to merge into another codebase later

- user: only contains username, email, password
- user profile: contains things like faves, bio, etc.

**Comment by xmatthewx** [comment]
<img width="1314" alt="user-profile-model" src="https://user-images.githubusercontent.com/53411/28840434-ebf4ff5a-76c4-11e7-8698-8d86443622b4.png">

My diagram doesn't include Favs. Are there other things missing that should be represented?

**Comment by Pomax** [comment]
PR landed!
