### ISSUE TITLE
Unblock access to admin

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#146]
I've lost permission access to the Pulse django admin. @hannahkane has as well. Caused by a recent update?

<img width="560" alt="screen shot 2017-07-05 at 1 03 30 pm" src="https://user-images.githubusercontent.com/53411/27875767-64149f70-6182-11e7-8ceb-e0c2345f0bb3.png">

cc @alanmoo @cadecairos @Pomax

**Comment by Pomax** [comment]
is_staff was set but is_superuser was not. That's been fixed
