### ISSUE TITLE
Add Help categories model for entries

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#155]
Specifically, a fixed list of 12 (?, ping @xmatthewx) types of "help" that can be extended by others that entry creators would like to illicit (e.g. "help use teach this", "help us with design", "help program", etc)

The work involved are:

- [x] model update
- [x] initial migration that inserts the 12 help types
- [x] API route for getting all help types
- [x] update to the API route for entry posting, to accept the set of relevant help-needed flags

**Comment by xmatthewx** [comment]
Categories developed based on analysis of existing requests for help on pulse entries. 

Categories : ['Attend', 'Create content', 'Code', 'Design', 'Fundraise', 'Join community', 'Localize & translate', 'Mentor', 'Plan & organize', 'Promote', 'Take Action', 'Test & feedback', 'Write documentation']

**Comment by xmatthewx** [comment]
Like our 5 issue categories...

 - An author can select help cats when they submit a new entry
 - An entry card will display selected help categories.
 - A user can tap a help category to view a list of entries at `/help/code`
 - ....?

**Comment by mmmavis** [comment]
@Pomax if you don't have too much on your plate can you take this one on? There are old tickets and PRs that I never got the chance to finish on Pulse and react-formbuilder so I'd like to use some time this milestone to get to them.

**Comment by Pomax** [comment]
server-side has been implemented, client-side not yet.

**Comment by xmatthewx** [comment]
Is this still a work in progress? Blocking #601 @mmmavis? Or done and good to close?

**Comment by mmmavis** [comment]
@xmatthewx we'll have to update API production when GitHub is back to normal. I don't have the rights to push to prod. @Pomax could you please help update it?

**Comment by xmatthewx** [comment]
alrighty. github seems good now. anything you want me to test on staging @mmmavis? thanks!!

**Comment by mmmavis** [comment]
I think we are good. Just need to hit the "push to prod" button.

**Comment by mmmavis** [comment]
@Pomax we can close this ticket now, right?
