### ISSUE TITLE
Decide on approach for Profile model

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#159]
consider:
 - user <> person profile
 - responsible <> organization/celebrity profile

profile fields: #612

**Comment by xmatthewx** [comment]
@gideonthomas feel free to weigh in on this estimate

**Comment by gideonthomas** [comment]
is "responsible" a special kind of user that would have their own person profile AND have a collection (that could be empty) of org/celeb profiles?

**Comment by xmatthewx** [comment]
Yes, that sounds right. User has a Profile; User in an Admin or Editor Group would have power to create a Profile for a Person/Organization that isn't necessarily a user. Could create several of those. In Django, we should be able to see who made the profile.

**Comment by xmatthewx** [comment]
discussed and done
