### ISSUE TITLE
Expose profiles in a way to enable linking of entries to creators 

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#169]

**Comment by xmatthewx** [comment]
When posting a new entry, users should be able to enter creators
 - [ ] see auto-complete options for existing profiles (first), existing creators w/o profiles (second)
 - [ ] enter new creators when one doesn't already exist

**Comment by gideonthomas** [comment]
Trying to figure out the difference between this ticket and https://github.com/mozilla/network-pulse/issues/624

**Comment by alanmoo** [comment]
This is kind of a subset of that other ticket. I updated that ticket's original comment as such.
