### ISSUE TITLE
make Entry auto-split tags with commas, and flag bad tags in Tag .save

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#180]
We should make sure that when saving an Entry, we check all tags for commas, and clean things up before the Entry is saved, so that Tag instances do the right thing.

The Tag model itself should probably also check for commas when they save just so we can cactch when things go wrong.

**Comment by xmatthewx** [comment]
@Pomax - is this a thing you could poke at in between PTOs

**Comment by Pomax** [comment]
that did not happen, can we put this in the upcoming milestone?
