### ISSUE TITLE
Add Languages to Profile model

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#194]
On Pulse, we will soon enable users to have a profile that displays info about themselves and lists their projects.  ([design mockup](https://redpen.io/qua34b5932cdb6cf9f))

We'd like to add Languages so users can identify languages they speak and find their peers across the network. 

This is nice to have in the future, not MVP to launch our first version of profiles.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
