### ISSUE TITLE
Connect 'Help Offered' to Profile model

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#195]
Entries on Pulse can be associated with `Needs Help` categories. If we extend Profiles to include corresponding `Can Help` categories, users and staff can start matching people with projects. Kaboom.  

This feature doesn't block initial launch of profiles, but would unlock a lot of power heading into MozFest.

**Comment by xmatthewx** [comment]
The two models match one-to-one in most cases.

| Help Needed | Help Offered |
| --- | --- |
| Attend | --- |
| Create content | Create content |
| Code | Code |
| Design | Design |
| Fundraise | Fundraise |
| Join community | --- |
| Localize & translate | Localize & translate |
| Mentor | Mentor |
| Plan & organize | Plan & organize |
| Promote | Promote |
| Take Action | ?? Activism ?? |
| Test & feedback | Test & feedback |
| Write documentation | Write documentation |

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
