### ISSUE TITLE
Add "location" field to profile model

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#197]
This will store city, (state), country in a format compatible with Google's location APIs.

cc @mmmavis 

Not sure who's going to actually work on this, unassign the other when you start.

**Comment by gideonthomas** [comment]
to clarify two things:
1. State may or may not be null right?
2. A profile can have only 1 location?

**Comment by mmmavis** [comment]
I've done some testing: https://github.com/mozilla/network-pulse/issues/675#issuecomment-327980100

I guess it really depends on what we wanna do with the location data in the future...

**Comment by xmatthewx** [comment]
We just want one `location` per profile that captures `city/town` and `country`. Nothing else is necessary for the platform. 

We will want the api to allow something like `search?keyword=paris` OR `/profile?location=paris`. We don't need to build that now, but should store things with that in mind.

**Comment by alanmoo** [comment]
I imagine we'll want to search by radius too? So people outside major cities can see stuff going on nearby.

**Comment by xmatthewx** [comment]
We could include State, but let's not worry about `near me` until we've landed totally landed `next to me` and have 1000+ monthly active users. We also don't have locations on entries since the majority are located _on the internet_ and we're intentionally not in the business of event management.

**Comment by mmmavis** [comment]
(See https://github.com/mozilla/network-pulse/issues/675#issuecomment-327980100 for my Google API tests)

This is the [sample result](https://jsonblob.com/42290da6-943a-11e7-80fd-75be2164b3ee) from searching "Vancouver" using Google API. I think we can just store what's in `terms` (we can discuss how we wanna design the model)

```
"terms": [
  {
    "offset": 0,
    "value": "Vancouver"
  },
  {
    "offset": 11,
    "value": "BC"
  },
  {
    "offset": 15,
    "value": "Canada"
  }
]
```
and maybe the `place_id` as well in case we need to retrieve more info about the place from Google API?

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
