### ISSUE TITLE
Lower profile's custom_name character limit

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#198]
@xmatthewx profile's custom_name character limit is currently set to `500`. Do we wanna reduce it to `140` or even lower? /cc @gideonthomas

**Comment by xmatthewx** [comment]
Oh yes. Good catch. 140 at the most. The internet says that UK govt recommends 70 chars for full name fields. Lets go with that? Longest currently in DB: 27.

**Comment by mmmavis** [comment]
Yea since it's "custom name" and not a person's full legal name I think we should def lower the char limit. `70` sounds good.
