### ISSUE TITLE
engineer 'nonce' out of existence

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#20]
I added the nonce protection to make sure forms aren't double-posted, but we might be able to do this by on the client making sure the submit button can't be clicked more than once, and on the server doing a content hashing to see another post by any user already matches the same data digest.

@alanmoo @mmmavis thoughts?

**Comment by alanmoo** [comment]
So you're saying if the server gets a second identical data set we'd ignore it? I like the idea of reducing the work the client has to do to assemble the request, but what kind of effort would it be to do the content hashing?

**Comment by Pomax** [comment]
in principle it's just non-crypto hashing (md5 or something) on some of the fields. For instance user X submitting title Y with desc Z - hash that triplet, and see if that is a known hash. I *think* that's a thing we can achieve with a property `def` in the model.

**Comment by alanmoo** [comment]
It feels like we're venturing close to (but not reaching) the built in behavior of Django to prevent duplicate entries. Is there any magic we can leverage?

**Comment by Pomax** [comment]
is this a real thing? Because when I went looking for it, I could not find any built in behaviour for that.

**Comment by alanmoo** [comment]
By duplicate entries, I meant the ability to tell Django that certain fields (like the title) must be unique, thus automatically preventing duplicate entries. This feels like a lot of over-engineering for the sake of allowing two entries with the same title, which I really don't see as necessary.

**Comment by Pomax** [comment]
We are opposed then: short titles are pretty much guaranteed to collide over the lifetime of this API (I am under the assumption this API will be running for years), and requiring they be unique turns our API from a technology that supports the internet to a Microsoft style "we only allow you to structure the internet the way we say you can".

So if the choice is between "forcing uniqueness on titles" and "use a nonce and make sure the client gets a new one when *it* knows the user's data is significantly different" I'd say let's keep the nonce.

That said, title isn't the only field we can look at - URLs are supposed to be universally unique identifiers, so rather than looking at the title, we could look at the content url and return a 400 along the lines of "someone already submitted an entry for this URL, its ID is: ...", in which case we wouldn't need the nonce anymore.

**Comment by xmatthewx** [comment]
People might submit the same URL a year later, with new information on the project. Or a different project by the same org. 

I'd rather see duplicates and manually moderate. Can we wait and see if this is a problem?

**Comment by alanmoo** [comment]
Ok, let's stick with the title fields as they are. @xmatthewx we're more concerned with duplicate posts in a row from the same user in this ticket, because the internet isn't perfect.

**Comment by alanmoo** [comment]
Oh nevermind, I see what you're saying. Also a good point.

**Comment by Pomax** [comment]
@alanmoo in that case do we want to just strip the nonce functionality, or should we put it behind a feature flag that for now is simply set to false? Both have their own merit.

**Comment by alanmoo** [comment]
Doesn't matter to me. I'd also be fine just leaving it as it is for now, as I feel like we've got other fish to fry. Unless it proves problematic to implement on the front end.

**Comment by Pomax** [comment]
wtf, let's leave this issue open until we've eaten all the big dishes.

**Comment by eman291** [comment]
> in principle it's just non-crypto hashing (md5 or something) on some of the fields. For instance user X submitting title Y with desc Z - hash that triplet, and see if that is a known hash. I _think_ that's a thing we can achieve with a property `def` in the model.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
