### ISSUE TITLE
Update README.md with instruction to use python 3.x for this project

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#203]
We should probably add the following to README.md (copied from the network-api README)
---

#### Important note for systems with python *and* python3

In order to make sure your virtual environment will be using python 3.x you will have to explicitly tell the system it should use point to `python3` whenever it invokes python:

```
$ virtualenv -p python3 venv
```

**Comment by Pomax** [comment]
that seems fair, want to file a PR?

**Comment by apoorvaagupta** [comment]
Hello, i am new to this project. can I take up this issue, if no one is assigned to it?

**Comment by Pomax** [comment]
hi @apoorvaagupta, sorry for the delay: if you're still interested, then absolutely! We just updated the README.md to a better structure and I don't think anyone added in that information yet.
