### ISSUE TITLE
add pagination to entries JSON response

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#21]
We're currently missing a {page,per_page} pair for the `/entries` route, which means there is no way to only grab 10 (or 5 or 20) entries at a time. We'll need to add something like https://docs.djangoproject.com/en/1.10/topics/pagination/#using-paginator-in-a-view to make sure we only send managable sets to the client.

**Comment by xmatthewx** [comment]
related front-end things https://github.com/mozilla/network-pulse/issues/235

cc @mmmavis
