### ISSUE TITLE
Handle multiple Redirect URIs

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#211]
As per [this ticket](https://github.com/mozilla/network-pulse/issues/684#issuecomment-329557602), it appears that [this line](https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/users/views.py#L43) only allows one redirect URI. But if we want to test multiple front-end environments using staging data, the API needs to be able to redirect to a different client side url for OAuth. Do we have access to headers so we're able to determine which URI to redirect to? If so, let's make that happen.

**Comment by Pomax** [comment]
This makes an assumption about how the process work that is incorrect.
- clients perform a call to the server to initiate the oauth2 process, with a query argument that tells the server where to go once oauth2 handshaking has concluded
- the server contacts google, with *its own oauth2 finalisation url as redirect_uri argument*, and the client's uri encoded as part of this authentication transaction state.
- google okays the oauth2 negotiation, and redirects to that `redirect_uri` with the negotiation state preserved
- the server records whether or not oauth2 negotiation succeeded or not, then unpacks the negotiation state, finds the client-indicated "go back to this URL when you're done" url, and causes a browser redirect to that URL

**Comment by alanmoo** [comment]
This works now. I think it was the case sensitivity of env vars.
