### ISSUE TITLE
Figure out how org profiles are created via admin

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#214]
Branching from https://github.com/mozilla/network-pulse-api/pull/212#issue-259916418, it looks like a user can "own" multiple profiles. I think we did this so that we could allow org profiles to be created without there being a corresponding user.

The problem is that since a user can have multiple profiles, it is hard to precisely pick out which of those profiles represents the user itself (i.e. is not an org profile). There is an `is_group` checkbox on profiles that seems to tell us if it is an org profile or not. Is that what we use to tell if the profile is an org profile or not? 

So, if user1 has profiles A, B, and C, profile B represents the user itself and the `is_group` checkbox is unchecked for that profile, is it safe to assume that profiles A and C are org profiles and their `is_group` checkbox is checked? Since this `is_group` toggle is controlled via admin, it seems risky to rely on profile creators to make sure that for their user, only 1 profile has `is_group` unchecked and all other profiles have it checked.

One thing to note is that no one actually needs to own a profile. The way our model is structured, a profile may or may not be associated with a user. This allows users to create org profiles and the way we can distinguish between org profiles and the user's profile is that the org profiles do not have a user attached to them while the user's profile is attached to the user.

Clarifications that can help fix this issue:
- What is `is_group` used to indicate?
- Do we care about who created an org profile?
- Can we rely on admins to make sure that out of all the profiles they create, only one has `is_group` unchecked viz. their profile?

**Comment by xmatthewx** [comment]
@gideonthomas - thanks for the thoughtful post. Some replies below. Let's discuss over video if helpful. 

In answer to your questions: 1) `is_group` indicates that a profile represents a group of people in the world. Functionally, it doesn't do anything. It will allow us to find these profiles later for potential future functionality. 2) We don't care who created a group profile, as long as only an Admin can create it via django. 3) No. An admin might create a profile for a celebrity partner that is not a group. For now, that profile can be an orphan with no association with the admin. A User, even an Admin, should only have one assiciated profile, for now. (notes of the future below)

Some strawfox guidelines that might be helpful:
 1. All `Users` should have one, and only one `Profile`. 
 1. Some `Profiles` can be created by an `Admin` and will have no associated `User`, aka _Orphan profiles_.
 1. These orphan profiles could represent an individual (e.g. internet celebrity partner) or be flagged `is_group`. (We trust Admins to get permission from person/group first.)
 1. Orphan profiles can be added to an `Entry` as a `Creator`.
 1. In the future, we _could_ create a model of `Owner` to associate a `User` with `Profile(s)` they manage. We don't need to explore this body of work until it proves necessary.
 1. In a more distant future, we _could_ create a model of `Group` to associate `Profiles` that are members of that group. Group would have one, and only one is_group profile. We definitely don't want to give that an ounce of thought until the stars align with the planets. In fact, forget that you read this item.

**Comment by gideonthomas** [comment]
thanks @xmatthewx, this clarifies a lot!

**Comment by gideonthomas** [comment]
@xmatthewx, can creators be orphan profiles?

**Comment by xmatthewx** [comment]
Yes, an orphan profile can be a creator. This lets a user name and credit a foundation, for example, on their entry.

**Comment by gideonthomas** [comment]
oh totally missed that, thanks!

**Comment by Pomax** [comment]
To clarify users can be linked to *many* profiles, but there can be only a single profile that is not a group profile for that user (i.e. describing themselves rather than a group/org/etc).

**Comment by Pomax** [comment]
Based on our call, the idea is to:
- set up profiles as unassociated data types
- modify users such that they can point to zero or one profile instances
- plan for, but don't implement yet, profile management of "not my profile" by users of the system
