### ISSUE TITLE
Creators should be objects with or without profiles

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#215]
**UPDATE**: This issue is now only about changing the way POSTing an entry works.

Followup from this: https://github.com/mozilla/network-pulse-api/pull/212#issue-259916418

We need to setup the API view to send a list of creators, separating those with and those without profiles. This is required to help with auto-complete when adding creators to an entry.

Part of this work also involves changing how posting an entry works. Right now, we match the creators' names entered in the front-end to any that we find in the db. If we find the same names in the db, we use that creator, if not, we create a new db entry for that creator. Simply put, we're keying on names which isn't sustainable.
We need to figure out how we want to modify the JSON payload sent when the front-end POSTs a new entry.

@mmmavis, we could use some input here:
1. How would you like to receive the list of creators for autocomplete? Something like:
```js
// `id` is the creator's id here
{
  "with_profiles": [{
    "id": 1,
    "profile_id": 2,
    "name": "Mavis"
  }, {
    "id": 2,
    "profile_id": 5,
    "name": "Pomax"
  }, ...],

  "without_profiles": [{
    "id": 7,
    "name": "Gideon"
  }, {
    "id": 9,
    "name": "Matthew"
  }, ...]
}
```
or just combined:
```js
// `id` is the creator's id here
[{
  "id": 1,
  "profile_id": 2,
  "name": "Mavis"
}, {
  "id": 2,
  "profile_id": 5,
  "name": "Pomax"
}, {
  "id": 7,
  "profile_id": null,
  "name": "Gideon"
}, {
  "id": 9,
  "profile_id": null,
  "name": "Matthew"
}, ...]
```
or something else?

2. How will you send the data when POSTing an entry. Right now only a list of strings are sent for creators. We now need to know instead when to create a new creator (does not exist in the db) and when to use one from the db (if it was autocompleted). What's your preference for how this is shown in the POST /entries json request payload?

**Comment by mmmavis** [comment]
@gideonthomas 

> 1. How would you like to receive the list of creators for autocomplete?

Let's go with the latter option but leave `profile_id` out since the "add entry form" doesn't link to anyone's profile. (true? @xmatthewx ?)

```js
// `id` is the creator's id here
[{
  "id": 1,
  "name": "Mavis"
}, {
  "id": 2,
  "name": "Pomax"
}, {
  "id": 7,
  "name": "Gideon"
}, {
  "id": 9,
  "name": "Matthew"
}, ...]
```

> 2. How will you send the data when POSTing an entry.

It might be worth looking at how `tags` are being handled in the backend as we have autocomplete for tags in the front end already. From what I can see front end is just posting `tags` as an array of strings... I wonder for `creators` if it should be an array of object that contains that person's `name` and `id` since we want to avoid mapping the wrong person in case his/her name isn't unique in the database.

Will something like this work?

```js
// `id` is the creator's id here
// order of creators matters
[{
  "id": 7,
  "name": "Gideon"
}, {
  "id": 1,
  "name": "Mavis"
}, {
  "id": null,
  "name": "new name/person"
}, {
  "id": 9,
  "name": "Matthew"
}, ...]
```

**Comment by gideonthomas** [comment]
Yeah, we can't use the `tags` flow for the reason you mention. But, we can totally accept the array you mention above, so let's stick to that.

Thanks for the clarification!

**Comment by gideonthomas** [comment]
Note on the above POST payload...technically, the `name` isn't needed for objects with the `creator id` not set to null, however, it might not be easy to add a condition to the serializer like "either id or name should exist" so we might want to do that part as a follow up.

**Comment by xmatthewx** [comment]
split into two tickets??

**Comment by gideonthomas** [comment]
Filed https://github.com/mozilla/network-pulse-api/issues/228

**Comment by gideonthomas** [comment]
Clarification here:
We want to make the API backwards compatible so that it doesn't break existing functionality.

For the POST /entries route, this ticket makes us change the `creators` property from an array of strings into an array of objects so that we can identify existing creators. This isn't necessarily easy to implement on the backend. 
Instead, I propose this:
1. We keep the existing `creators` property to be an array of string creators representing creators that don't exist yet on the backend and are not profiles.
2. We add a new property called `creators_with_profiles` which is an array of objects where each object is like:
```js
{
  "creator_id": <number or null>,
  "profile_id": <number or null>
}
```
Here's the three possibilities for the above object:
- `creator_id` is null, `profile_id` is a number - a profile was autocompleted but we don't have a creator existing for that profile yet
- `creator_id` is a number, `profile_id` is null - a string creator that was autocompleted and already exists on the backend but is not associated with a profile
- `creator_id` is a number, `profile_id` is a number - a profile was autocompleted and we have a creator existing for that profile.
Technically, the last two cases can be combined so that it basically amounts to two cases: first, if a creator id is provided, we use that (whether it's associated with a profile or not), or second, creator id is null but a profile id is provided so that we create a new creator for that profile.

@mmmavis, let me know if this makes sense or not

**Comment by gideonthomas** [comment]
It looks like this might depend on some of the conversation happening  in https://github.com/mozilla/network-pulse-api/issues/228

@xmatthewx, can we discuss after stand tomorrow?

**Comment by mmmavis** [comment]
@gideonthomas +1 I think this discussion deserves a quick Vidyo call. In tomorrow's meeting (assuming we are having one) we should also talk about how we can preserve the ordering of the creator list in the front end form.

**Comment by gideonthomas** [comment]
darn I forgot about the ordering...yeah we won't be able to have two separate properties.
