### ISSUE TITLE
Most of the Entry's fields should be optional

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#22]
## Required

- title
- content_url
- published_by (correct me if I'm worng - we can pull this directly from the logged in user profile and there's no need to have it on the submission form.)

## Optional

- description
- thumbnail_url
- tags
- get_involved
- get_involved_url
- interest
- internal_notes
- featured
- issues
- creators

/cc @kristinashu @xmatthewx

**Comment by mmmavis** [comment]
Sorry just checked `models.py` and seems like there are more fields we should make them optional. I'll update the ticket description soon.

**Comment by mmmavis** [comment]
Ticket title and description have been updated!

**Comment by kristinashu** [comment]
Looks right to me!
