### ISSUE TITLE
Add Snyk vulnerability monitoring

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network-pulse-api#221]
Let's add a Snyk vulnerability check on our dependencies in this project. See https://github.com/mozilla/network/pull/733 for reference.

also, [Snyk docs](https://snyk.io/docs)

**Comment by Pomax** [comment]
What is this "Snyk"?

**Comment by anweshknayak** [comment]
@cadecairos can I take this up?

**Comment by patjouk** [comment]
It's done, I'm closing this issue 🎉
