### ISSUE TITLE
Custom name change doesn't get propagated correctly

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#226]
STR:

- go to Django dashboard and edit custom name on your own profile
- verify that Dashboard shows the new custom name
- visit `/api/pulse/myprofile/` to verify if the `custom_name` returned is up to date
- bug: `custom_name` is still the old value

**Comment by mmmavis** [comment]
Um weird. It's working fine for me now. Was it really cacheing issue then? @gideonthomas 

Anyways, closing this ticket now 😉

**Comment by gideonthomas** [comment]
not sure :P

**Comment by mmmavis** [comment]
Oh technology! 😏
