### ISSUE TITLE
Setup API for searching creators

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#228]
We need to setup the API view to send a list of creators, separating those with and those without profiles. This is required to help with auto-complete when adding creators to an entry.
The payload should look something like this:

```js
// `id` is the creator's id here
[{
  "id": 1,
  "name": "Mavis"
}, {
  "id": 2,
  "name": "Pomax"
}, {
  "id": 7,
  "name": "Gideon"
}, {
  "id": 9,
  "name": "Matthew"
}, ...]
```

cc @Pomax

**Comment by gideonthomas** [comment]
One thing we want to consider is that we might want to expose profiles for which we don't have creator objects on the backend yet as well so that it can be autocompleted in.

**Comment by Pomax** [comment]
As both a performance and security measure, we should absolutely not send a blind list, only sending 200 responses after we get search queries with one or two letters. Until we have at least _something_ to refine a search on, we should probably send a 409 or something.

**Comment by xmatthewx** [comment]
> we might want to expose profiles for which we don't have creator objects on the backend yet as well so that it can be autocompleted in.

When a new Profile is created, can we create the corresponding creator object? So it's good and ready for autocomplete queries?

**Comment by xmatthewx** [comment]
> The payload should look something like this:

Should this also include `profile_id` when a creator has one?

**Comment by gideonthomas** [comment]
I think we can create a creator as soon as a profile is created! @Pomax, what do you think?

Agree about refining results vs. sending all possible creators.

> Should this also include profile_id when a creator has one?

I don't think we need the profile_id if a creator already exists for the profile. If however we want to link autocomplete results to profile pages (which I would advocate against in the interest of time), we would need the send the profile id.

> I'm also not sure we need the actual id as known to the system in the response...without ever exposing database internals

I'm not sure I follow. Why is the `id` something we want to make private? You can't really do anything with that information that we don't allow + we already expose active profile ids to the client. Resolving creators into random strings and storing them in the session (and then resolving them back to creators) sounds complicated; I feel like using the `id` would be the simplest solution but let's address your security concern.

**Comment by xmatthewx** [comment]
> I don't think we need the profile_id if a creator already exists for the profile.

We definitely don't need to link to to profiles. But, don't we need to distinguish which creator's have and don't have a profile? That allows us to list Gideon (has profile) before Gideon (doesn't have profile). We could also indicate to users which have a profile. So I figure we need `has_profile` or `profile_id` to indicate this.

**Comment by Pomax** [comment]
This solves the "profile + creator" issue, can we conceive of a situation where we have a creator object, without an associated profile? (I think no?)

**Comment by Pomax** [comment]
This probably relates back to #215 too now

**Comment by xmatthewx** [comment]
> can we conceive of a situation where we have a creator object, without an associated profile?

Yes. As a submitter of a new entry, I can name daffy duck as a contributor on my project, regardless of whether mr duck has ever used pulse or logged in to create a profile.

**Comment by Pomax** [comment]
The API route will be invoked as:
```
http://test.example.com:8000/api/pulse/creators/?search=...
```
where `...` is any string.

This will return data of the form:
```
{
    "count": 123,
    "next": "http://test.example.com:8000/api/pulse/creators/?page=2&search=...",
    "previous": null,
    "results": [
        {
            "profile_id": number or false,
            "name": "..."
        },
        ...
    ]
}
```

The `count` represents how many hits the system knows about, `next` is a URL if there are more results than fit in a single result set, or `null` if there are no additional pages of results. The `results` property points to an array of actual creator records, where each creator has a `name` (string data) as well as a profile_id (either a number if the creator has an associated profile, or `false` if the creator does not have an associated profile).

**Comment by gideonthomas** [comment]
@Pomax we also need the creator id
