### ISSUE TITLE
Enable `featured` query param 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#23]
Please enable `featured` query param to allow filtering entries by the `featured` boolean.

This will be useful for the /featured page on Pulse: https://pulse-react.herokuapp.com/featured

**Comment by alanmoo** [comment]
This is just set in the admin panel with no need for other endpoints around this flag other than the filter, right?

**Comment by xmatthewx** [comment]
I think that's correct. In the future, we should give admins the power to toggle the feature flag via the frontend, but we don't need that now.
