### ISSUE TITLE
add a login hook so that users can be redirected to their profile

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#231]
building on https://github.com/mozilla/network-pulse-api/issues/230, we need to implement a post-login hook so that users can be checked to see if they've visited their profile and if not, redirect them to the profile rather than to their original url-of-login.

Note that if the user's indicated redirect_url is the `/add` page, then no profile-redirection should happen at all, and the user should always end up on the /add page, but with a notice to tell them to check out their profile if the backend knows they have yet to view their profile and run through profile FTU

**Comment by alanmoo** [comment]
Will we have a way to preserve what page the user is coming from so that once they've finished the profile page, their original flow can resume?

**Comment by Pomax** [comment]
This feels like a past station. would you agree @xmatthewx?

**Comment by Pomax** [comment]
It feels like an issue to close, and when we eventually get to a new "let's figure out some improvements" and this matters, we can refile.
