### ISSUE TITLE
`is_bookmarked` regression - user's bookmarked entry has `is_bookmarked` set to false

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#233]
STR

1. make sure you are logged in
2. visit the `/api/pulse/entries/bookmarks/` route to see the list of your bookmarked entries
3. check the `is_bookmarked` property in each Entry object
4. on localhost/staging all of them are set to `false` (should be `true`). On production `is_bookmarked` are properly set to `true`

https://api.mozillapulse.org/api/pulse/entries/bookmarks/
https://network-pulse-api-staging.herokuapp.com/api/pulse/entries/bookmarks/

**Comment by xmatthewx** [comment]
Is this worth discussing on tomorrow's stand? cc @alanmoo to help us remember.

**Comment by Pomax** [comment]
Hm, the fact that it landed on staging suggest the tests for bookmarking still pass, so we may need to do a bit of digging @gideonthomas

**Comment by gideonthomas** [comment]
@Pomax sorry, I fix this in my current patch which isn't on staging yet
Basically it's just how we're accessing `request` from the `context` in the serializer that's wrong.
