### ISSUE TITLE
Add created entries to /profiles/<id>

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#234]
As per https://github.com/mozilla/network-pulse/issues/742#issuecomment-335670891, we need to add created entries to the public profile view.

Changes need to be made to:
https://github.com/mozilla/network-pulse-api/blob/b2f12cfd19e66523dcf3fcb6d79c65032aa8edcc/pulseapi/profiles/serializers.py#L81-L100

**Comment by xmatthewx** [comment]
who should take this @alanmoo?

**Comment by alanmoo** [comment]
@Pomax @gideonthomas I added both of you on this, just give a shout when one of you starts it so the other doesn't.
