### ISSUE TITLE
Make Creator admin more user-friendly

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#244]
Creators that are associated to profiles have their `name` field empty. If someone fills it out in the admin, it is ignored. This is a point of confusion.

Some good changes to make to the Creators admin:
1. Have a toggle "Does this creator have a profile" and selectively show either the profile dropdown or the Name field accordingly.
2. Add a "Name that will show" field that is read only and is pre-populated with the creator_name.
   - Bonus - update that field as either the Name or Profile field changes.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
