### ISSUE TITLE
Improve developer ergonomics

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#258]
We should focus on making this repo easier for people to spin up for the first time.

- [x] Generate fake data for local use (#196) 
- [x] Make sure environment defaults are set to work in a localhost environment, including OAuth when locally hosting the client-side repo. (Consider CSP settings and the like)
- [x] Update readme to make sure it reflects the current best way to set up for use with a locally hosted client-side repo.

There's probably more to this, whoever starts on this should do a clean install and take notes on what they have to do to get things working correctly.

**Comment by alanmoo** [comment]
@cadecairos @patjouk I tagged this DevOps for visibility, might be good slow-day type of work.

**Comment by cadecairos** [comment]
> including OAuth when locally hosting the client-side repo

This just won't work without editing your /etc/hosts file. Google Oauth on localhost. For local development we should just stick with username/password authentication to the admin site.

**Comment by alanmoo** [comment]
Are you talking about having test.example.com point to localhost? If that's a requirement of testing OAuth that's fine. But we should have it in the docs, so that we do know how to test it if needed.

**Comment by cadecairos** [comment]
Marking this resolved, if there's further ergonomic related work lets open a new ticket.
