### ISSUE TITLE
Determine API versioning approach

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#259]
There seem to be 2 reasonable approaches to API versioning- `v1, v2, v3...` and date based APIs. Based on the volume we have right now, is using version numbers a fine approach?

Whatever we go with, we need to identify how we'll add/deprecate parts of the API going forward. For example, when we needed to change `creators` from an array of strings to `related_creators` as an array of objects, we should have had a way to call the API in such a way that the old `creators` key wasn't used anymore (for performance reasons), but leave it in there for consumers of old versions of the API. Beyond that, we should be able to identify consumers still using old API versions before we deprecate them so we can update those sites accordingly/notify their owners.

Once we've determined approach, we should file another ticket to implement the current version as v1

**Comment by patjouk** [comment]
@Pomax mentioned in a previous issue (#184) that Django REST Framework provides tools to do [API versioning](http://www.django-rest-framework.org/api-guide/versioning/). That's definitely something we should investigate.

**Comment by alanmoo** [comment]
That seems like a very logical choice. Closing and filing another ticket.
