### ISSUE TITLE
Entry model should have a timestamp field

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#26]

**Comment by Pomax** [comment]
what does this timestamp represent? datetime the entry got posted?

**Comment by mmmavis** [comment]
I believe so (cc @kristinashu for confirmation).

**Comment by kristinashu** [comment]
Yes, same as on production site. Example "Added Dec 12, 2016" https://mzl.la/pulse?id=p12122016154012

**Comment by mmmavis** [comment]
I assume this won't be hard to implement so I've labelled this ticket as "MVP for Pulse Launch". If it's not a simple task we can wait postpone this ticket till later.
