### ISSUE TITLE
Content Moderation Guide (discussion)

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network-pulse-api#268]
_From https://github.com/MozillaFoundation/mofo-devops-private/issues/103 :_

We're asking contributors to provide data about projects that could include PII. Our reviewers and (staff that submit content) should be aware of what data we can and can't make publicly available.

* Can we add some kind of section to the Admin area to remind people what is appropriate and what's not. (i.e. "don't approve the publishing of PII")
* Can we add information to the submission forms about what data is or is not appropriate?

I'm hoping we can identify if any changes need to be made to help us moderate the content we post.

**Comment by xmatthewx** [comment]
Yep. We can do both. We have some phrases on the profile form. I took a stab at others below. Does this work?

Profile form
 - [x] Bio (do not include any personal information)
 - [x] Profile pic (only submit photos you have permission to use in this context)

Entry form
 - [ ] Description (do not include any personal information)
 - [ ] Get Involved (do not include any personal information)
 - [x] Project image (only submit images that you have permission to use in this context)

Moderators view
 - [ ] Note: Look for personally identifiable information that should not be made public

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
