### ISSUE TITLE
extend Profile with additional fields

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#271]
Based on https://github.com/mozilla/network-pulse/issues/657, the Profile model should be extended with several fields that are "standard fields", and several fields that should only be exposed when the "show this profile's extended information" flag is set to true.

General fields for MVP:
- location, as free form text

Extended fields:
- `show_extended` boolean flag to toggle extended field visibility
- `program` (MVP: a single program)
  - `program type` choice selector for known programs
  - `program year` year selector with a reasonably short number of years up to and including whatever year is reasonable but at least the current one
- `affiliation` free form text
- `bio_short` field with 212 character text
- `bio_long` field that takes arbitrary length text content

For the "bio long" we probably want some upper limit to the number of characters, but that's a limit we can iterate on.

**edit** based on https://github.com/mozilla/network-pulse/issues/657 the fields became:

- `profile_type` fixed list of profile types (see 657)
- `show_extended` boolean flag to toggle extended field visibility
- `program` (MVP: a single program)
  - `program type` choice selector for known programs (related-field, admin-curated)
  - `program year` year selector with a reasonably short number of years up to and including whatever year is reasonable but at least the current one (related-field, admin-curated)
- `affiliation` free form text
- `bio_short` field with 212 character text
- `bio_long` field that takes arbitrary length text content

**Comment by xmatthewx** [comment]
Should we call this done?

**Comment by gideonthomas** [comment]
Closing as done. Feel free to re-open if I'm wrong.
