### ISSUE TITLE
Pulse and Pulse API on the same server

### ISSUE THREAD

**Issue by lguariento** [mozilla/network-pulse-api#273]
Hello,

I would like to deploy Pulse and the API on the same server (CentOS). I have successfully installed Mozilla Pulse, which answers on port 3000. I have also set up a Python virtual environment inside the network-pulse-api folder and successfully started the Django server on port 8001. I already have port 8080 busy, so I'm running http-server on 8000. Now, though, when I go to myip:8000/ I successfully get the 'A test post to http://test.example.com:8000/entries' page; the submit button is greyed out though: is this normal?

Also, my network-pulse on port 3000 just returns 404 on every GET request to myip:8000/api/pulse/ (userstatus, login, etc). Why? I have

`PULSE_API=http://myip:8000/api/pulse`

in my config/default.env for network-pulse.

Thanks in advance!

**Comment by lguariento** [comment]
I found the issue - it was with the http-server, which is now correctly serving the /public/ folder. I already have port 8080 busy,so I'm running it on 8000. Now, though, when I go to myip:8000/ I succesfully get the 'A test post to http://test.example.com:8000/entries' page; the submit button is greyed out: is this normal?

Also, my network-pulse on port 3000 just returns 404 on every GET request to myip:8000/api/pulse/ (userstatus, login, etc). Why? I have

`PULSE_API=http://myip:8000/api/pulse`

in my config/default.env for network-pulse.

Thanks in advance!

**Comment by alanmoo** [comment]
I believe there's a `PORT` key supported by the Pulse client. My local `.env` looks like this (though this file has evolved over time and as it's gitignored, I'm not entirely sure everything is accurate):

```
# HOST=the host you are using
HOST=http://localhost

# PORT=the port number you are using
PORT=3000

# PULSE_API=URL to your local Pulse API instance. Remove this var if you don't have one set up.
#PULSE_API=http://test.example.com:8000/api/pulse

# PROJECT_BATCH_SIZE=Number of projects you want to display as a batch.
# Make sure this number is divisible by 2 AND 3 so rows display evenly for different screen sizes.
PROJECT_BATCH_SIZE=24
```

**Comment by lguariento** [comment]
Thanks @alanmoo . The Pulse client works indeed on port 3000, no problem with that. My problem is reaching the API.

```
PULSE_API=http://test.example.com:8001/api/pulse
PULSE_API=http://myip:8001/api/pulse
PULSE_API=localhost:8001/api/pulse
```

They all fail to do what I want, and when the Pulse client calls them I get 404. Is there something I'm missing?

**Comment by lguariento** [comment]
PS: should I be able to reach the Django server? Pointing my browser at the port Django is running gives me an 'unable to connect' error, thought the server is running with the runserver command.

**Comment by alanmoo** [comment]
You should be able to reach django (localhost:port/admin), so that's likely your issue- something isn't hitting the right port/directory.

**Comment by alanmoo** [comment]
Try `SSL_PROTECTION=False` in your `.env` file for pulse-api as well, since locally you don't have https.

**Comment by lguariento** [comment]
Thanks. Yes, I had a problem with my Django server indeed! I can now reach it. But I still have the 'submit' button greyed on the 'A test post to http://test.example.com:8000/entries'. I cannot access the Django admin and add entries from there. Nevertheless, they don't show up on the main Pulse page - I just get the 'loading' gif. I feel I'm so close to the solution... am I missing something?

**Comment by lguariento** [comment]
PS: just to make things clear: Django is running on port 8000, and http-server on 8001. On the http-server console I keep getting 404 errors such as

`"GET /api/pulse/login?original_url=http%3A%2F%2Fmyaddress%3A3000%2Ffeatured" Error (404): "Not found"`

**Comment by lguariento** [comment]
Ah, it works now! I forgot to add my domain to the `CORS_ORIGIN_WHITELIST` in setting.py.

**Comment by lguariento** [comment]
Now the 'only' issue I have is that the 'Signup / Signin' button redirects to '?loggedin=False' without further error messages, just a `302` code on the logs. The only way I can login is to log in to the Django administration and then go back to the Pulse website. Weird...

**Comment by Pomax** [comment]
if you want to use "real" login you will have to set up google authentication through google's administrative console, otherwise you can also use `http://localhost:8000/admin/login` to log in directly with the superuser account.

**Comment by DigiTransGlasgow** [comment]
Setting up google authentication through google's administrative console it's exactely what I've done (see below). Is there something I'm missing?

**Comment by lguariento** [comment]
PS: sorry, I sent the above message from another account - it's still me. Also, see #276 for updated on my issue (which is still ongoing)
