### ISSUE TITLE
Redirected to loggedin=False even if login is successful

### ISSUE THREAD

**Issue by lguariento** [mozilla/network-pulse-api#276]
Hello,

this might be related to #273 . When I click on the signup/signin link I am successfully redirected to the Google signin page. I choose a Google account, I input the password, and the Google authentication is completed successfully. In fact, if I open a Google page I see that I am logged in. The problem is that after authenticating I get redirected to the original Pulse url with `loggedin=False` appended, with the result that I am not logged in to the Pulse website. Why do I get a `loggedin=False` redirect from the Google authentication page despite the fact that I login to Google with the correct credentials? Is there a parameter of some sort I'm missing somewhere?

**Comment by alanmoo** [comment]
When you say "redirected to the original Pulse url" do you mean on your local machine?

**Comment by lguariento** [comment]
I mean http://myip:3000/featured?loggedin=False. I'm trying it on another computer on the same network.

**Comment by alanmoo** [comment]
Did create a Google Oauth application and set the redirect urls appropriately?

(BTW, if any of this could be cleared up by updates to the documentation we'd really appreciate a pull request when it's solved!)

**Comment by lguariento** [comment]
Yes I did; also because if the redirect urls are not appropriately set Google would display an error message (which I got when they were not set appropriately). As I said, if I open a new tab on google.com I appear logged in; not on the Pulse website, though.

PS: very happy to contribute to the documentation! I've also a couple of questions about deployment, and I'm happy to contribute to that section too once I deploy it. Let me know which 'channel' is better for discussing that.

**Comment by lguariento** [comment]
Just to clarify my situation: I have a CentOS virtual machine with ssh access only, where I installed node.js, the Pulse application via npm and the Pulse API on a python virtual environment. I access it via browser on the same network.

**Comment by alanmoo** [comment]
@Pomax or @mmmavis may have some guidance on this, I can't recall the specifics of how the auth flow works off the top of my head.

**Comment by lguariento** [comment]
Thanks Alan, hopefully @Pomax or @mmmavis will be in touch and help me solve this issue. I really want to like Pulse :) .

**Comment by Pomax** [comment]
hmm, if you log in from the client, there is a callback argument that is "the current URL" you are on, and if the python server authentication works, you should be getting a callback to that URL with the loggedIn flag set to true... can you detail the journey from being on the client page in the browser and about to log in, to being back in the client after logging in, in terms of which URLs you hit in succession? 

E.g. 
1. localhost:3000/featured
2. localhost:8000?login&...
3. google.com/....
4. localhost:8000?...
5. localhost:3000/featured?...

(there's probably more than five)

**Comment by lguariento** [comment]
Here is a video: ﻿﻿﻿https://www.dropbox.com/s/muvkfs3s6pc001g/authentication.mov?dl=0

**Comment by Pomax** [comment]
Hm, I'm missing the bit where you're initiating the login from the client: what do you have set as client and server env values, and what is in your client_secrets.json? (feel free to of course replace client id/secrets with placeholder values)

**Comment by Pomax** [comment]
On a side note, I'm quite curious how you found pulse and why you're trying to run it for yourself =)

**Comment by lguariento** [comment]
You didn't miss much, I simply clicked on the upper-right signin button!

My default.env for network-pulse is:

```
HOST=http://localhost
PORT=3000
PULSE_API=myip:8000/api/pulse
```
My client_secrets:

```
{
    "web": {
	"auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "client_id": "myid.apps.googleuserconten$
        "client_secret": "mysecret",
        "redirect_uris": [
            "myip:8000/api/pulse/oauth2callback"
        ],
	"token_uri": "https://accounts.google.com/o/oauth2/token"
    }
}
```
The 'public' folder of the api is served by http-server on port 8001, the Django app is running on port 8000, and Pulse is running on 3000.

I work for a project which sort of collect a number of other AHRC research projects... actually we might get in touch privately to discuss this, perhaps you can help me with some customisation (provided I manage to get it working!).

**Comment by Pomax** [comment]
Hmm, to rule out anything that might be related: is that `client_id` of the form "bunch of digits, dash, 32 alphanumeric symbols"? There should not be anything that looks like a domain in it (you need to remove that from the client id if it's still in there).

**Comment by lguariento** [comment]
Yes, precisely as you say - bunch of digits, dash, 32 alphanumberic symbols.

**Comment by Pomax** [comment]
nice. What is your API .env content? Mine is:
```
DEBUG=True
SSL_PROTECTION=False
REDIRECT_URIS=http://test.example.com:8000/api/pulse/oauth2callback
```

**Comment by lguariento** [comment]
```
DEBUG=True
REDIRECT_URIS=http://myip:8000/api/pulse/oauth2callback
SSL_PROTECTION=False
```

**Comment by Pomax** [comment]
at this point it looks like everything is technically set up correctly, so the only way to figure out what's going wrong is to do some code diving.

https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/users/views.py#L165-L192 is the code that the API server uses to send the user back to the client they initiated the login with, but the loggedIn query argument is passed in as a function argument as part of the auth callback, which starts at https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/users/views.py#L196, and can either be `false`, in which case https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/users/views.py#L235-L238 kicked in, or it can be `true`, in which case https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/users/views.py#L240-L260 kicked in.

You may need to start putting some `print(...)` statements in this function to see what the various state values are, to determine what might actually be happening here.

**Comment by lguariento** [comment]
a-ha: I-ve found some ugly red errors on my console while logging in. Stuff like:

`
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src 'nonce-M4obBtzzXdGVay0udPDiiHpkPm0' https://accounts.google.co.uk 'unsafe-eval' https://apis.google.com https://ssl.gstatic.com https://www.google.com https://www.gstatic.com"). Source: ;!function(){var t=0,e=function(t,e){ret....`

And also:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://myip:8000/api/pulse/entries/?featured=True&page=1&ordering=-created&page_size=24&format=json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

I already put my host in the `CORS_ORIGIN_WHITELIST`, I don't understand. Any ideas?

**Comment by lguariento** [comment]
OK, I put 'allow all' in the CORS settings (which is not ideal of course, but fair enough) and I don't get the CORS error now. I definitely fet a bunch of those `unsafe-eval` errors thoguh, which appear as to be the issue.

**Comment by Pomax** [comment]
hm, my CORS section looks like this:
```
# we want to restrict API calls to domains we know
CORS_ORIGIN_ALLOW_ALL = False

# we also want cookie data, because we use CSRF tokens
CORS_ALLOW_CREDENTIALS = True

# and we want origin whitelisting
CORS_ORIGIN_WHITELIST = os.getenv(
    'CORS_ORIGIN_WHITELIST',
    'localhost:3000,localhost:8000,localhost:8080,test.example.com:8000,test.example.com:3000'
).split(',')
```

**Comment by Pomax** [comment]
out of curiosity, is your browser running any script/html blocking extensions like privacy badger, noscript, etc?

**Comment by lguariento** [comment]
Yes, I have whitelisted my IP already in the CORS_ORIGIN whitelist.
And I've done the same thing with a fresh Safari app with no extensions (I only use Firefox) and it does the same thing. I get redirected to the Google authentication, put email and password, and then redirected with the `False` flag. If I click on the plus button (for adding new items, top right) it just tells me:

```
Sign in failed
Sorry, login failed! Please try again or contact us.
```

I didn't alias test.example.com, because that machine has its own name on the local network and I am using that one (I only have ssh access on it, and I'm accessing it from another machine on the same network).

**Comment by lguariento** [comment]
> The unsafe-eval etc. are CSP restrictions, not CORS errors

Yes - I mentioned CORS because I actually had a specific CORS error, which I temporarily solved by putting 'allow all' in the CORS settings.

**Comment by Pomax** [comment]
Can you log what the values are as the callback function is run through? It's pretty hard to debug without a way to reproduce this, so print statements are pretty much all we can go on in terms of helping you debug this.

**Comment by lguariento** [comment]
I managed to grab the output (I was making a silly mistake and looking somewhere else). Name and email are passed correctly, and  I also output an authentication code of 55 digits. The problem is that the `loggedin` variable is printed out as false, after grabbing the correct name/email.

**Comment by alanmoo** [comment]
@ryanwarsaw I think this is the problem you were having too, is that right?

**Comment by lguariento** [comment]
Also, print(str(error)) returns `False`

**Comment by ryanwarsaw** [comment]
@alanmoo That is correct, after reviewing this issue I can confirm I'm able to replicate this issue on my macOS High Sierra machine `10.13.2 (17C205)`on Chrome `63.0.3239.132` and Firefox. 

`network-api` appears to be operating normally, there is an XHR request error I'm experiencing in the output, the issue seems to reside almost entirely on the `network-pulse` side. Will investigate when time permits, this is certainly an issue. A mildly infuriating one at that! 💯

**Comment by lguariento** [comment]
It's good to hear it's not just me, @ryanwarsaw. The application + API are running on a Centos 7.4.1708 and I get the same error on the latest Firefox, Safari, and Chrome. If you need any other information, just ask away!

**Comment by Pomax** [comment]
Closing this issue as out of date
