### ISSUE TITLE
Expose user ID in `userstatus` endpoint

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#281]
To help address https://github.com/mozilla/network-pulse/issues/916, we need an easy way to access the user's id. If a user is logged in, we should add another key to `/userstatus` with their ID.

**Comment by alanmoo** [comment]
@gideonthomas Just a gut check: this should be pretty easy and seems like the correct approach, right?

**Comment by gideonthomas** [comment]
yeah, changes need to be made here: https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/users/views.py#L104-L115

**Comment by bhavyaagg** [comment]
Hello,
If no one is currently doing this can i take up this issue?

**Comment by alanmoo** [comment]
Yes, please!

**Comment by bhavyaagg** [comment]
Thank you @alanmoo
