### ISSUE TITLE
Enable moderator to add a creator to existing entry

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#289]
Currently, a moderator can add a new Tag to an existing Entry. They can do this via django by either editing the Entry or the Tag. A moderator can't, however add a Creator to an existing entry. Not via an edit of the Entry or the Creator. 

Is there a limitation that blocks this? Or, can we turn this on?

In terms of interface, it is _much_ easier to associate a Tag and Entry via the edit Tag UI. Django offers a discreet field for each associated Entry. From the edit Entry UI, a moderator has to search and dangerously select all associations in a single multi-select box.

**Comment by gideonthomas** [comment]
This should be done, closing.

**Comment by xmatthewx** [comment]
yipee! nicely done. @alanmoo we can now add creators to existing entries if we get a request. though let's test a request before we promise.

**Comment by alanmoo** [comment]
Just saw it on staging, awesome and perfect interface for that kind of thing! Looks like it needs to be promoted to prod tho. @xmatthewx There is a request in the queue for just this kind of thing, want to give it a swing once we promote?

**Comment by xmatthewx** [comment]
works like a charm
