### ISSUE TITLE
Add a /entry/entry_id endpoint

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#29]
This would be very useful for single entry view on Pulse.

**Comment by Pomax** [comment]
do we not have this already?

**Comment by Pomax** [comment]
@mmmavis we have this already, `http://test.example.com:8000/entries/1/` will give you the result in pretty HTML, which is generally useless, and `http://test.example.com:8000/entries/1/?format=json`  will give you a nice JSON object. 

In my setup with some dummy entries, the above url gives me
```
{"id":1,"tags":[],"issues":["Online Privacy & Security","Decentralization"],"creators":[],"title":"first entry","description":"generic description","content_url":"http://example.com/1","thumbnail_url":"http://example.com/1/thumb.jpg","get_involved":"Don't get involved~","get_involved_url":"http://example.com/1/gi","interest":"http://example.com/1/gi/thumb.jpg","featured":false}
```

**Comment by Pomax** [comment]
https://github.com/mozilla/network-pulse-api#current-api-end-points

**Comment by mmmavis** [comment]
YAY awesome! thanks @Pomax 😄
