### ISSUE TITLE
Add current git commit to status route

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#290]
Once https://github.com/mozilla/network-pulse-api/pull/284 lands, we'll have a `/status` route. Currently it only returns the `latestApiVersion` but we could also add the current git commit sha to the response as well. This might be a little tricky since heroku doesn't really give you the git commit.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
