### ISSUE TITLE
Response of /api/pulse/profiles/? endpoint should include profile id and location meta

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#291]
Partial mockup of Fellowships site's directory page:

<img width="490" alt="screen shot 2018-02-09 at 5 51 53 pm" src="https://user-images.githubusercontent.com/2896608/36057368-f73413d0-0dc1-11e8-86a8-5bfb5afa4bfc.png">

(Note that "SEE WORK" links to that fellow's Pulse profile)

We'll need  `/api/pulse/profiles/?` endpoint to return `location` and `profile id` so we can feed these meta into fellowships' directory page.

/cc @Pomax @alanmoo

**Comment by Pomax** [comment]
both PRs have landed.
