### ISSUE TITLE
Determine how to update Pulse API for better performance around querying profiles

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#292]
Right now project details are shown for every project a profile is associated with. This slows down performance of the API dramatically. We should add options to include or not include project details.

Output required to close this ticket:
An approach (endpoints, query params, what data gets shown)
A ticket to actually do the work

**Comment by Pomax** [comment]
we might also want to look at not making this one end point, but several, so that a client asks for

- a profile
- a list of created entries associated with that profile
- a list of published entries associated with that profile
- etc

This would cut out a large amount of joins, moving the responsibility of crosslinking to the client, which makes a lot of sense when looking at an individual profile already anyway.

**Comment by alanmoo** [comment]
Something like `/api/pulse/profile/2`, `...profile/2/createdEntries`, and `...profile/2/publishedEntries`?

**Comment by xmatthewx** [comment]
Cool. I wonder if we want a slight variation, filter for more flexibility. `profile/2/entries` vs `profile/2/entries?rel=created` vs `profile/2/entries?rel=published` vs `profile/2/entries?type=news`. We don't currently have types (news, project, curriculum), but that feels imminent.

**Comment by alanmoo** [comment]
So, how's this (some of it may already be in place):

`/profiles?type=` - some filtered amount of profiles
`/profile/{id}` - a specific profile without published/created/fav'd entries
`/profile/{id}/entries` - all entries* related to a user grouped by created/published/favorited (Is this one even necessary though or is it just a performance risk?)
`/profile/{id}/entries?rel={created,published,fav}` that specific subset of entries* related to a profile

\* Entries returned this way should expose:
  * ID
  * Title
  * Image
  * IsBookmarked
  * related_creators
  * moderation_state (?)
  * created

Anything else should only be exposed if it comes by default without impacting performance

**Comment by xmatthewx** [comment]
**related people:** published by would be a good idea if we getting creators. though, are we getting creator names or ids? names are probably a performance hit. i wonder if we can skip all these associated names. it's slightly weird to omit attribution, but not crazy to expect views to open the project to view its info. 

**moderation state** first thought: we should only expose approved entries. second thought: if a user publishes a thing being held in moderation, they might expect to see it somewhere on their profile. this sounds complicated. let's forget i said this.

**Comment by alanmoo** [comment]
I'm looking at the content that's on the cards right now, and `published by` isn't there (though obviously it will be the same user when fetching `rel=published`). So I'm not sure where this would come in and be useful- we'd do a proper fetch for the entire entry's details when a user clicks on it. I believe creators are a performance hit, but I'm trying to keep the request consistent based on what's needed for the current design.

Moderation state: I'm fine not including that and requiring all returned entries to be approved, though if we later on wanted another query (`/profiles/{id}/entries?rel=published&moderation=all` for example), we'll need to add it.

**Comment by xmatthewx** [comment]
I think your approach is solid and flexible. 

We can adjust what gets pulled to frontend as needed based on the scenario. Showing favs in pulse is very different than listing fellow entries on the site directory in terms of attribution.

**Comment by alanmoo** [comment]
@gideonthomas Do you have thoughts on this before we convert it into an actual task?

**Comment by gideonthomas** [comment]
Yeah, the approach is fine. Just three minor thoughts:
1. I don't follow `/profiles?type=`...what is it expected to do?
2. We can add `/profiles/{id}/entries` and have it return all of its entries or maybe an entry count (will be less of a performance hit). Probably best if we don't hit it on the front-end but we would need it for the next route to work.
3. I suggest changing `/profiles/:id/entries?rel={created|published|favorites}` to:
   - `/profiles/:id/entries?created`
   - `/profiles/:id/entries?published`
   - `/profiles/:id/entries?favorites`
   - `/profiles/:id/entries?published&created` and other combinations (it's easy to implement)

**Comment by alanmoo** [comment]
1. This isn't precise syntax, it's for the filtering that's [already in place](https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/profiles/views.py#L80-L82).
2. Great
3. Great

I'll distill this into a proper ticket next and then close this.
