### ISSUE TITLE
rename favorites to bookmarks for developer clarity

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#30]
also update the readme (and probably add code comments) to explain exactly what we mean with bookmarking, and if bookmarks needs to be "settable" then we probably want to split up the PUT route to not be a toggle, but be two distinct "set" and "unset" routes.

**Comment by alanmoo** [comment]
Can you remind me why we're using a different terminology than the front end, which is sticking with "favorites"?

**Comment by Pomax** [comment]
short version "because that's what we compromised on". I still *want* both the backend and front end code to call it bookmarks to remove any ambiguity, but that was not afforded to us, so at the very least we can remove that ambiguity in the code where it is the most important that the vars and classes are named in accordance with what they are used for in code.

**Comment by mmmavis** [comment]
If things on backend have been renamed from favorites to bookmarks I will do the same on front end codebase. Filing ticket now.

**Comment by alanmoo** [comment]
I thought we were sticking with favorites on the front end.

**Comment by mmmavis** [comment]
honestly... I'm still pretty confused at this point. I know we want the functionality on front end stay unchanged but I'm unsure if we've decided to keep the current naming or not. 😕

**Comment by alanmoo** [comment]
@kristinashu can you comment?

**Comment by kristinashu** [comment]
Front end should stay as is, we're keeping favorites.

**Comment by Pomax** [comment]
This might need just a little more clarification: the front end consists of two parts, namely "the code, that only devs see", and "the UI, which the user sees". We're keeping the user-facing parts using labels like "favorite", but are also saying the for-dev-eyes-only code has to keep using "favorites"?

/cc @xmatthewx

**Comment by kristinashu** [comment]
Sorry, I'm talking about the UI.

**Comment by xmatthewx** [comment]
I think the questions is.... where can we best handle a wee bit of confusion? As long as the user facing stuff remains Favs, I'll let the engineers decide where we need to add some comments to explain the shift in names from bookmarks to favs. Let's not worry about it too much. I'll shoulder any fallout later.

**Comment by Pomax** [comment]
@kristina @xmatthewx noted - keeping it favs on the UI side makes a whole bunch of sense. For "the code" I'll file a follow-up issue on the network-pulse repo
