### ISSUE TITLE
Enable Org/Orphan Profiles

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#305]
Staff and moderators should be able to create a Profile for Organizations that can be linked to entries as a Creator. We should have a clear method to add a Profile for both new and existing Creators. 

 - [x] As a moderator, I want to create Creating new profiles for Organizations that are not currently listed as Creators on our platform, so that future submissions can be associated with this Organization.
    - [ ] On Change Profile form, is_active is confusing. We should either default to true or add a note to check the box for new profiles. 
 - [ ] As a moderator, I want to create a profile for existing Org Creators so visitors can view all entries associated with that Organization.  
    - [ ] On Change Creator view, user should be able to tap `+` to create and associate a new profile
    - [ ] On Change Creator view, Profile drop-down should list profiles by Name, not Email address. Moderator my not know a user's email address and orphan profiles do not have one and are all listed ambiguously as orphan profile. 
   
## New Profile – Creator does not exist (this works)

 1. Go to [django/profles/userprofile](https://pulse-api.mofostaging.net/admin/profiles/userprofile/)
 2. Tap Add Profile
 3. Fill out form
    - does author have to select is_active? can this default to true?
 4. Save Profile
 5. Add a new entry
 6. Add org as creator with autocomplete

   
## New Profile – Creator exists (this does not work) 

 1. Go to [django/creators/creator](https://pulse-api.mofostaging.net/admin/creators/creator/27/change/?_changelist_filters=p%3D1)
 2. Find and edit a creator such as [Mozilla](https://pulse-api.mofostaging.net/admin/creators/creator/27/change/?_changelist_filters=p%3D1) or [Mouse](https://pulse-api.mofostaging.net/admin/creators/creator/148/change/?_changelist_filters=p%3D1)
 3. Tap the `+` icon next to Profile to create a new profile. 
 4. Complete Add Profile form
 5. Tap Save
     - This currently returns an error: "Creator with this Profile already exists." Strange since profile was just created.

## Association

Let's list association by name, not email. Moderators might not know a user's email address. And, all orphan's appear the same. 

![image](https://user-images.githubusercontent.com/53411/36683786-7f91bb06-1aec-11e8-91ef-82dba6bcf09f.png)

**Comment by alanmoo** [comment]
The orphan profile label in the `select` has been fixed, replaced by the custom name from the profile. We should have an indicator on that list if it's a profile attached to a user account or not when we switch to names for all options.

**Comment by xmatthewx** [comment]
As discussed in slack, we will pursue the ability of the /profiles/userprofile/ID/change/ form to select a Creator. This will unblock the creation of Org/Orphan Profiles for people/orgs already named as a creator.

**Comment by gideonthomas** [comment]
@xmatthewx does https://github.com/mozilla/network-pulse-api/issues/319 supersede this?

**Comment by xmatthewx** [comment]
Yep. I think you've unblocked these things enough. We can close this. As we refactor in #319, let's spec out admin things as well.
