### ISSUE TITLE
Bug: “enable extended info” checkbox doesn't seem to do anyting

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#311]
The “enable extended info” checkbox on profile editing admin doesn't seem to work. (extended info seems to be always enabled regardless of the checkbox state)

<img width="482" alt="screen shot 2018-02-26 at 12 41 20 pm" src="https://user-images.githubusercontent.com/2896608/36695735-00cf97ec-1af7-11e8-9114-4a09e1865292.png">

I left it unchecked but those meta below still got included in the response of `/pulses/?profile_type=fellow` API call. 

/cc @Pomax

**Comment by xmatthewx** [comment]
It is a little confusing, but I think it's okay if admin continues to display the fields. It allows staff to compose content before they're ready for it to go live.

If extended is true, API should... 
 - return fields with request for a profile
 - accept data in updates on profile 
   - (frontend edit form should display these fields. this work is coming soon on the roadmap.) 

If extended is false, API should...
 - not return fields with request (whether there is data or not)
 - not accept data on updates
   - (fronend edit form should not display these fields.)

**Comment by alanmoo** [comment]
I believe this is the case already. Perhaps @gideonthomas can confirm

**Comment by mmmavis** [comment]
Is the extended profile boolean by default toggled on? Who gets to decide whether or not a user can have extended profile? I think it's worth to figure these out early as it will affect the what form fields we should show on front end.

**Comment by gideonthomas** [comment]
Right now the extended profile is off by default. Someone who has access to the admin needs to turn it on for a profile and then you will see the extended fields in the responses for that profile. I think the description that @xmatthewx has provided is already the way the API works (let me know if I'm wrong about this).

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
