### ISSUE TITLE
Discuss Github integration (for global sprint)

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#312]
Pulse allows a user to link to their project and link to get involved info. Sometimes, these link point to a github repository. The repo has valuable info for project leads, visitors, and program staff. 

 - As a user I want my projects on pulse to link to make my github link and activity more visible. 
 - As a staff program manager, I want to gather stats on my program's impact. 
 - As a visitor I want to explore projects with strong activity and preparation for contributors. 

Let's use this thread to discuss the value, the possibilities, and the constraints and figure out what an MVP first step might be. 

cc @acabunoc @alanmoo @gideonthomas

**Comment by xmatthewx** [comment]
A few thoughts to start us off....

## User input

I see two options: 
 - a user checks a box to identify that their get involved URL is a github repo
 - or, on submission, we sniff both URLs to see if they're github

Adding a new field in the form seems unnecessary. We could, however, have a dedicated field for github URL in the database. If someone links to [reponame]/blob/master/README.md for get involved, we could store repo URL in that field. GH URL format is consistent and should be easy to handle.

## Data gathering

When we have a known repo, we can gather a few types of info: 
 1. contributor prep booleans: has contribute.md, readme, license, etc...
 1. counting stats: stars, forks, contributors, days since last commit
 1. activity: log of stuff

The first two seem useful and fairly easy. We could update each time a project is viewed. Minimal overhead. The third seems very resource intensive and less useful. It would require regular cronjobs on entries and repos that might be dormant. This job would have to be run on an independent server ... otherwise it risks squashing user activity during an event like mozfest. 

## Data display

Visitors and program staff would benefit from seeing some data on entries based on their openness and community engagement. It would also be nice to have some aggregate info on a bunch of entries by tag, like mozsprint.

**Comment by xmatthewx** [comment]
We should think about how to prototype this with OLE team and the community. Two reasons: 
 - there's lots of ways this could be done right and wrong, hard to guess, better to test.
 - realistically, we'll have limited time on the team to do this thoroughly

I propose that we: 
 1. Add `github_repo_url` field to the entry model on api and backend admin. Maybe auto populate this on a new submission when it includes a github url in the existing form fields. 
 1. Work with @acabunoc @auremoser to find someone to leverage api to make a prototype a view of projects with github data.

**Comment by auremoser** [comment]
I would :+1: making github URL a separate field; there's a ton we can do with that, and I think we can automate other checks if necessary (like look for readme and contributor file).

**Comment by acabunoc** [comment]
+1 I like the github URL as a separate field. @zee-moz was asking about linking directly to the README, and leveragivng the github api would help with that.

**Comment by alanmoo** [comment]
@gideonthomas we discussed some of these things a while ago. Do you have any thoughts?

**Comment by gideonthomas** [comment]
Speaking with @acabunoc there are two main goals here:
1. To track activity in the global sprint and store it somewhere
2. Enhancing the view of an entry with a github repo link to show additional data about the repository.

I was told that not all projects will be in pulse, so I don't recommend implementing the first one in pulse itself and rather, have another server that does this.

The second one we can do in pulse, but we need to determine value of that vs. the first one (if we don't intend to do both) with the global sprint team.

@xmatthewx and @alanmoo, would you be able to mention what the deliverables/priorities are here?

**Comment by alanmoo** [comment]
Collecting the activity for the Global Sprint is the more pressing goal.

**Comment by gideonthomas** [comment]
Ok, in that case, we should write a cron job that will get all these stats and write it as json to a file in S3.
@acabunoc said that she would provide a list of global sprint project urls so it'll be easier to use that instead of dynamically figuring it out via pulse. We can eventually add pulse integration if we need it.

@alanmoo what do you think?

**Comment by alanmoo** [comment]
That was my instinct, though someone I spoke with was very against cron jobs, can't remember who. I don't recall a better solution though.

**Comment by gideonthomas** [comment]
@cadecairos my instinct is that it was you lol (sorry if I'm wrong). Do you have any thoughts?

**Comment by xmatthewx** [comment]
This is done as it's going to be.
