### ISSUE TITLE
Enhance Creators Admin list with search

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#317]
The view for Pulse at /admin/creators/creator/ could be improved a bit. 

 - [ ] add search form
 - [ ] add filter to show creators with and without profile (skip if complicated)

@gideonthomas this would be helpful. Not as critical as your other related work.

**Comment by gideonthomas** [comment]
doesn't the first one already exist?

**Comment by xmatthewx** [comment]
It does now! I don't think it was there before your latest PR. On Profiles, but not Creators. Closing...
