### ISSUE TITLE
Enable or default to reverse order on entries from profile endpoint

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#324]
Profiles currently display related entries in chronological order. Reverse chronological would be better, especially for profiles like [Mozilla's](https://www.mozillapulse.org/profile/209) that contain a dozen or more items.

The entries endpoint allows ordering with `?ordering=-created`. But they `published_entries` and `created_entries` cannot be ordered on `/profiles/<profile_id>` 

Again, default to reverse is fine. I don't see a big need for custom ordering, but that's fine too. 

Unblocks https://github.com/mozilla/network-pulse/issues/934

cc @alanmoo to triage and assign.

**Comment by xmatthewx** [comment]
@alanmoo this is resolved now by #326, correct?

**Comment by alanmoo** [comment]
No, #326 addresses the order of profiles that are returned, but not entries within a profile.

**Comment by alanmoo** [comment]
Looks like this was deployed.
