### ISSUE TITLE
Add the ability to merge profiles via the admin

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#327]
Branching off from https://github.com/mozilla/network-pulse-api/issues/319#issuecomment-370899444, we want to provide the option to merge profiles via the admin to resolve duplicate profiles that might crop up.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
