### ISSUE TITLE
Return entries in reverse order

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#335]
As per https://github.com/mozilla/foundation.mozilla.org/issues/119, we really should simply return all entries in reverse order by default. The cases in which we'd want to see entries from 2016 before today are few and far between, and we have an ordering option if we really want it. This isn't a breaking change, so we don't need to worry about versioning this either.

**Comment by xmatthewx** [comment]
So any current requests for `?ordering=-created` will continue to get latest item first? They won't reverse the reverse? If so, that's good.

**Comment by alanmoo** [comment]
Correct. Technically my PR will return sorted by `-id` instead of the previous `id`, which is different than `created` in name but not in practice.
