### ISSUE TITLE
Add fake data to staging?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#339]
Would it be possible to dump in some fake data to staging? Currently staging Pulse API only have ~10 fellow profiles that I manually added. With such a small data set it makes Fellowships Directory work (on Foundation site) hard to test (on review apps especially). Ideally we should have a few fellow profiles for each category (fellowship year, program type, etc)

/cc @alanmoo

**Comment by cadecairos** [comment]
@mmmavis Review apps should now generate a bunch of fellows in varying programs/years. It looks like staging has fellowship data now, so do we need to generate some there still?

**Comment by mmmavis** [comment]
@cadecairos I just checked - Foundation staging now seems to use Prod Pulse API. In that case we can just rely on the fellow profiles pulled from Pulse Prod instead of using fake data.

I think we can close this ticket now.
