### ISSUE TITLE
Update behavior of bookmarks/favorites

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#34]
* [x] There should be a filter that shows the current user's favorites as a list of entries
* [x] Entries list should have a key "isFavoritedByCurrentUser" as a boolean
* [x] Entries admin should have count of favorited users
* [x] Admin should have a list of entries that a user has favorited (if it's easy)

Anything else @mmmavis?

**Comment by mmmavis** [comment]
The list looks good to me. I think bullet 3 and 4 are good-to-have.

> Entries admin should have count of favorited users.

Is this how many times an entry has been favourited(unfav'ing doesn't affect this number)? Or how many users currently have this entry favourited?

**Comment by alanmoo** [comment]
The latter

**Comment by alanmoo** [comment]
Looks like all of these are already in the PR except the first, and that shouldn't take long to add as it's just like the featured filter.

**Comment by alanmoo** [comment]
`/entries/bookmarks/` will give a list of bookmarked entries by the currently logged in user.
