### ISSUE TITLE
Enable staff to edit and associate tags

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#343]
We recently set up new roles and permissions. It's all looking fab. 

If possible, it would be great to allow staff to edit tags. @zee-moz, for example, needs to add the mozsprint tag to a bunch of projects. 

api.mozillapulse.org/admin/tags/tag/[ID]/change/

@cadecairos @gideonthomas @alanmoo - thoughts?

**Comment by gideonthomas** [comment]
This is done @xmatthewx?

**Comment by xmatthewx** [comment]
done. thanks!
