### ISSUE TITLE
Use the live API for documentation

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#353]
Our current method of documenting routes in the README is not sustainable. Not just for reading the routes, but also changing the docs is very cumbersome. 

Ideally we would document the API on the live staging url and just point to it in the README thus keeping our readme clean. We could use the documenting tool built into DRF or use a nice thirdparty library like drf-yasg, drf open api, or drf docs.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
