### ISSUE TITLE
pyflakes 1.4.0 is incompatible with flake8 3.4.1

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#360]
Got this error from `pip install -r requirements.txt`. We should probably update our `requirements.txt`

<img width="957" alt="screen shot 2018-05-01 at 2 49 33 pm" src="https://user-images.githubusercontent.com/2896608/39495374-ec62ba66-4d4e-11e8-952d-2c06f3cc93fb.png">

**Comment by patjouk** [comment]
I'm taking care of it in #365 ;)
