### ISSUE TITLE
Plan how to expand profile model for Organizations 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#362]
A profile can be used for people and institutions. Let's discuss:
 - additional metadata useful for orgs
 - use of the existing is_group flag to distinguish

We have the mapping project, mozfest, and eyebeam as usecases to help shape this discussion.

**Comment by xmatthewx** [comment]
Notes and discussion here: https://docs.google.com/document/d/1K2C42LN5eLSUsXqDD0QZN_Rw3mbxqALTA_6KRcnnXDw/edit#

**Comment by xmatthewx** [comment]
@gideonthomas - would you call this finished? i think next step is ticket your work from a high level.

**Comment by gideonthomas** [comment]
Yeah I think this can be closed
