### ISSUE TITLE
Discuss Long Bio field

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#369]
@gideonthomas - how is the long bio field set up? can it take multi-paragraph text, preserving line breaks? 

Long term, I think we'll want this as a field that can take basic html for links and style. I'm not sure we want to tackle that now. 

cc @alanmoo

**Comment by gideonthomas** [comment]
It should be able to handle multi-paragraph text right now.

Basic html/links/style is a little more complicated. Can you give an example of a scenario where this would be useful?

**Comment by xmatthewx** [comment]
multi-paragraph is good enough for now.

there's a desire to get story engine interviews into this field. i think they contain links. maybe section headers. maybe italics. we could limit it to inline styles, no block level elements, no images.  

but... let's not tackle this now. let's just confirm we can handle line breaks in text.

**Comment by gideonthomas** [comment]
Ah ok, that makes sense. I think it's doable if in this case we get to control the content going in via the admin, i.e. we're vetting the content for security purposes.

**Comment by gideonthomas** [comment]
long bio already supports markdown...closing
