### ISSUE TITLE
Add support for ordering entries

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#37]
Via query param.

Date submitted
Number of Favs

Anything else? @mmmavis

**Comment by Pomax** [comment]
what would ordering on favs yield?

**Comment by alanmoo** [comment]
Updated original: for sorting by how many times an entry has been fav'd

**Comment by Pomax** [comment]
Hmm, I thought we weren't exposing that information in the client, is this used to create a curation-less "trending" page?

**Comment by alanmoo** [comment]
This isn't necessarily for launch, but I'm sure it's something we'll need at some point, no?

**Comment by Pomax** [comment]
ah, fair enough. backlog for now then?

**Comment by mmmavis** [comment]
Yes by date submitted would be super handy! And +1 on putting favs count in the backlog for now.
