### ISSUE TITLE
Allow custom ordering of profile entries

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#370]
For the `/profiles/<id>/entries/` route, let's allow specifying an ordering flag for each of the three types of entries, something like `?favorited_ordering=`, `?created_ordering=`, and `?published_ordering=`.

**Comment by xmatthewx** [comment]
great. thanks. let's do reverse by default. honestly, i don't see a need for oldest first.

**Comment by xmatthewx** [comment]
@gideonthomas - is this a thing we can look at this week?

**Comment by gideonthomas** [comment]
yep, I can work on it
