### ISSUE TITLE
add support for alternative modes of authentication

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#377]
We're using google login atm, let's enable a few more options so that people don't have to ask staff to post for them. Suggested options:

- google
- github
- anything social option that works as off-site login.

**Comment by xmatthewx** [comment]
Great. I suggest we start by adding just one, maybe Github. 

Question: if a user has the same email address associated with both services, will we see them as one user or two? Just curious. We don't have to solve this.

**Comment by Pomax** [comment]
I half-suspect they'll be considered a different user but I don't know how django's social auth package does email reconcilliation

**Comment by Pomax** [comment]
apparently if we add `social_auth.backends.pipeline.associate.associate_by_email` to our backends, it should treat different logins for the same email as "the same user".

**Comment by alanmoo** [comment]
I've got a meeting set up next week to learn a bit more about IAM and what that might enable us to do (or not)

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
