### ISSUE TITLE
Identify additional image sizes to use

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#378]
Problem: Pulse images are used at a variety of sizes across the Pulse client and the Foundation site. We shouldn't be displaying full sized images for gallery pages, or for pages built on the Foundation site.

At All-Hands we determined we should generate a few different sizes of all our images for easy use in different contexts. Let's determine what image sizes they should be in this ticket, then use that to inform #345's approach.

Areas where these images are used currently:

https://mozillapulse.org homepage view (and other card views)
Pulse entry view (https://www.mozillapulse.org/entry/835)
https://foundation.mozilla.org/opportunity/artists-open-web/ (warning, giant page)
I'm unsure if they actually are being used this way, but consider twitter/facebook share images too.

Anything else I'm forgetting?

**Comment by gvn** [comment]
Talking with Taís and looking at Pulse & Foundation, it looks like we should start with at least these 2 sizes generated on the server:

Small: 700px width (max)
Large: 1460px width (max)

**Comment by taisdesouzalessa** [comment]
Those 2 sizes suggested by Gavin cover the scenarios we have for all image sizes. If the image size is closer to the large, we can load large. If closer to small, we load small.

Here is a matrix with all possible widths we have at the moment. See it in RedPen: https://redpen.io/ge7fdc9958b070f540
<img width="861" alt="image" src="https://user-images.githubusercontent.com/22157921/41629620-64ed7168-73df-11e8-8504-3358b60382cd.png">

When I choose to tweet from Pulse, we don't display any image: 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/22157921/41629710-dfaf4aa2-73df-11e8-8f59-1deae9d3a3d2.png"> - it would be a nice feature to add in the future, I'll open a ticket for that.

**Comment by taisdesouzalessa** [comment]
@alanmoo was your question answered in this ticket? Let me know what you need as a deliverable (not sure if the numbers we got here are enough). If it is, I'll close the ticket.

**Comment by xmatthewx** [comment]
@taisdesouzalessa - let's pick a 3rd size, like a small icon or avatar. We don't do use this yet, but one use case would be to put tiny faces next to the names listed below a project. These should be cropped square. 96px? 144px? Probably good as a multiple of 16, our base font size.

**Comment by Pomax** [comment]
Perhaps an odd question: has anyone not-us done the deep dive into which sizes make the most sense across a web property? this feels like something AirBnB or the like would have pretty solid guidelines for, too, that we can incorporate into a decision around which specific sizes we need to save, and which we'd need to "invent on the fly"

**Comment by xmatthewx** [comment]
> aren't we just talking about the image sizes of the Pulse project heroes, or are the avatar images also too large?

Yes? I'm sure we have a similar problem with too large profile images. We can tackle that later, but hopefully, we have some fairly universal sizes that work for both scenarios. 

I mentioned tiny avatars b/c that use case is quick to understand, but I could also see us putting tiny project thumbs on a Fellow's profile card in the directory. So 96px would be useful for that.

**Comment by taisdesouzalessa** [comment]
Is this still relevant or should I close? @xmatthewx

**Comment by alanmoo** [comment]
I’m going to unsubscribe from this thread, but I believe we never really addressed the bigger issue of image performance on the foundation site; I vaguely recall mention of this being looped in with other planned work during all-hands in a convo with @cadecairos, so I’ll loop him in and see myself out.

**Comment by taisdesouzalessa** [comment]
I am unassigning myself from this thread. I will assign @jamilasnell to decide what to do with this thread and work.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
