### ISSUE TITLE
Add support for multi-line content in long bios

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#381]
Multi-line text pasted into the admin form is squashed into a single line. So paragraphs and lists don't work. This should work for submissions from our frontend and via django.

**Comment by xmatthewx** [comment]
cc @mmmavis

**Comment by mmmavis** [comment]
Not sure if this is easily doable - can we just make that field a `textarea` instead of a single-line `input` box?

**Comment by xmatthewx** [comment]
I assume Django has a preferred way to handle this in the model. Any thoughts @gideonthomas? A quick fix?

**Comment by gideonthomas** [comment]
linked a pr that should fix this

**Comment by alanmoo** [comment]
If that PR does what it needs, will the front end work without additional changes?

**Comment by gideonthomas** [comment]
sorry, maybe this needs to be two separate tickets and I misunderstood. The pr only fixes the admin side of things as mentioned by @xmatthewx. Is there still pending work on this in the frontend @xmatthewx?

**Comment by alanmoo** [comment]
That's what I'm asking too- does this fix make the front-end POST automatically work with newlines, or is more work required?

**Comment by alanmoo** [comment]
Wait. I might be having a moment. The front end doesn't actually do anything yet.

3 days till vacation.

**Comment by xmatthewx** [comment]
I think we're good. Client display has markdown support, so it should respect newlines. Client form doesn't yet have a field to submit this content. Coming soon.
