### ISSUE TITLE
Remove character count for profile long bio

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#383]
There's no need for one

**Comment by xmatthewx** [comment]
Shouldn't we have a some limit to prevent nefarious submissions? 100,000 characters?

**Comment by gideonthomas** [comment]
yeah we can add a limit, the frontend would need to handle errors though

**Comment by xmatthewx** [comment]
no problem. we can follow up with that. low risk if we set the limit is silly high.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
