### ISSUE TITLE
Add is_active to entry related creators

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#389]
We need to add the flag to the serialized data to make sure the front-end doesn't link to it.

**Comment by xmatthewx** [comment]
If this isn't too tricky. I'd like to prioritize this. I'm sharing Pulse with a few other orgs (Datakind and a Tech-for-good accelerator), and I think it will make the platform feel much more active and polished.

**Comment by gideonthomas** [comment]
I can work on this within the next few days
