### ISSUE TITLE
Create model/views for org profiles

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#396]
New model called `OrganizationProfile` in the `profiles` app.

Fields:
Organization name - Text with max char count, required
Headquarters Location - Text with max char count, required
Tagline - Text with max char count of 140, required
About - Text without max char count, required
Profile administrator - Foreign key to UserProfile
Twitter Handle - url
LinkedIn - url
Org email - email
Website - url
Logo - image
Internet Health Issues - Many to many field to `Issue`

GET route `/profiles/organizations/` to list all organizations (serializer can return all data)
GET route `/profiles/organizations/<id>` to get a single organization

**Comment by cadecairos** [comment]
Profile refactor is here: https://github.com/mozilla/network-pulse-api/pull/403

I got to here implementing the Org profile class: https://github.com/mozilla/network-pulse-api/tree/organization-profile-class

**Comment by Pomax** [comment]
Closing this for now, if this is still required work let's refile and redo, because the code has changed enough to make this "new work" instead of "finishing up an older PR".
