### ISSUE TITLE
Add is_active flag to profile serializer

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#404]
Let's return the `is_active` flag in all the profile endpoints for `v2` of the API.

Use Case: https://github.com/mozilla/network-pulse/issues/980#issuecomment-413727349

**Comment by ali-alsabbah** [comment]
Hi, I'm interested in taking a look at this if you want to tell me where to start

**Comment by gideonthomas** [comment]
Hi @ali-alsabbah, you can start by following the instructions in https://github.com/mozilla/network-pulse-api#getting-up-and-running-for-local-development to set up pulse on your local computer. Once you have it up and running, I believe you just need to add the `is_active` field to the profile serializers in [this file](https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/profiles/serializers.py). Once you do that, you should add a test to the https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/profiles/test_views.py file to test for the `is_active` flag in the serialized response.

Let us know if you have any questions and we'd be happy to help.

**Comment by ali-alsabbah** [comment]
Sure, I'll take a look at this over the next couple of days.

Thanks.

**Comment by ali-alsabbah** [comment]
Alright, I've followed the instructions up to the point where I'm asked to set up a Google client. It doesn't seem to me like I need to do that for this, do I?

Also, I'm not sure where and how to add the is_active field. For the test_views.py file, it seems like there's already a test for is_active (line 426), no?

**Comment by ali-alsabbah** [comment]
I've just submitted a pull request, take a look and let me know if any changes need to be made.

Thanks for your help.
