### ISSUE TITLE
Add Entry Type model

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#405]
For a while now, users have leveraged Pulse for a few different types of content. We'd like to distinguish them with a new model. We don't do anything fancy with it right now beyond filtering in api, but down the road, these types could extend an entry with new fields. 

types include: news, curriculum, info/research, project (default). Consider challenge or problem.

let's discuss @gideonthomas

**Comment by cadecairos** [comment]
😢
