### ISSUE TITLE
[AUTH CLEANUP] Fix admin login redirects

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#417]
## Things to fix

- **Scenario:** Go to `/admin/` as an anon user
**Expected behavior:** Redirects you to the main login page `/accounts/login/?next=/admin/`
**Actual behavior:** Redirects you to the admin login page `/admin/login/`

- **Scenario:** Logout of the admin site
**Expected behavior:** Redirects you to the API homepage `/`
**Actual behavior:** Shows you a page that says "log in again" which takes you to the admin login page

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
