### ISSUE TITLE
Polishing migration data

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#43]
It looks like 3 entries on the Google Sheet don't have a URL. @xmatthewx can you add something to them, since that's a required field for the new database?

Also, unless I'm missing something, we're dropping a few of the fields from the current entries:

* Favorites (to be regenerated in the new database)
* Status (Will be brought back in the future for community submissions)
* Suggestions & Feedback (does this go to "Internal notes"?)
* Network Connection
* Origin
* Program
* Type
* Backup thumbnail URL (I think this is from moving to hosted images, and fine to drop?)

Is this all correct?

**Comment by mmmavis** [comment]
I'm pretty sure we can drop "Backup thumbnail URL"... as that was one column I was supposed to remove but forgot 😂  Not 100% sure about the other ones but I assume those are okay to drop as well. I'd wait for @xmatthewx 's response.

**Comment by xmatthewx** [comment]
All looks good @alanmoo 

 - **Suggestions**: you can drop this. These were suggestions/feedback about the platform itself. 
 - **Network Connection**: let's map this to `Internal Notes`. 
 - **Origin**. Can we join this and merge this into `Internal Notes`? If not, drop it. 
 -  You can drop the rest.
