### ISSUE TITLE
Separate overloaded /nonce into /userstatus and /nonce

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#44]
In order to make the client work "cleaner", we should split up the `/nonce` route:

- `/nonce` should yield the values required for form posting: `{ nonce: "...", csrftoken: "..." }` or 403 if user is not authed
- `/userstatus` should yield `{ username: "...", email: "...", loggedin: true }` or `{ loggedin: false }` if user is not authed

thoughts @mmmavis @alanmoo ?

**Comment by alanmoo** [comment]
Makes sense to me
