### ISSUE TITLE
Enable search of Profiles

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#453]
Pulse now has 100+ fellows and 2000 profiles overall and 500 that include at least one social link. Useful stuff! Let's make it more useful by enabling search for profiles. 

To keep things simple, we can keep this search separate from project search. We will figure out a simple way for users to toggle between them. 

 - Search fields: `custom_name, affiliation, user_bio, user_bio_long, location`
 - Useful filter field: `profile_type_id`
 - Return by `id desc`

**Comment by gideonthomas** [comment]
should be fairly easy to add to the API

**Comment by xmatthewx** [comment]
@alanmoo - this would be a great issue for someone to pick up on a quiet day.

**Comment by gideonthomas** [comment]
I'll do this today...looking for something low-key to do as I recover.

**Comment by gideonthomas** [comment]
@xmatthewx what information will be shown on the front-end in the search list? Trying to optimize for performance because it's really slow at the moment.

**Comment by xmatthewx** [comment]
Thanks @gideonthomas. I think we can stay within the userprofile model. No need to pull in related stuff.

```
search:
	custom_name,
	user_bio,
	location,
	affiliation, // nice to have
```


```
return:

	id,
	custom_name,
	is_active,
	is_group,
	thumbnail,
	user_bio,
	affiliation,
	location,
	profile_type_id, // nice to have
	program_type_id, // nice to have
	program_year_id, // nice to have

```

**Comment by gideonthomas** [comment]
extended info should be easy to do. As long as we don't need to include any entry info, I think we're good performance-wise.
