### ISSUE TITLE
Serve images based on aspect ratio query

### ISSUE THREAD

**Issue by youriwims** [mozilla/network-pulse-api#458]
The API needs to be capable of serving optimized, uploaded images to specific aspect ratios/dimensions based on a query parameter.

Use-case: Currently on the foundation site, I am trying to render Fellow images from Pulse at a 1:1 aspect ratio, but the current system doesn't allow me to do that solely with the URL that is being served.

cc: @patjouk

**Comment by Pomax** [comment]
corresponding issue over on the foundation repo: https://github.com/mozilla/foundation.mozilla.org/issues/2687

**Comment by Pomax** [comment]
Depending on the "physical" size we need, we might be able to do some python resizing magic, and sending the profile headshots over as base64 strings either as part of the API response, or on a dedicated route, like `api/profiles/<id>/thumbnail`

**Comment by Pomax** [comment]
Headshots would be 192x192 x1, 384x384 x2, so that would pack on probably about 10kb in compressed JPG per profile - that makes it impractical to add it as BASE64 string in the API response itself, but makes it quite suited for serving up as dedicated API response on a `/profiles/<id>/thumbnail` route.

@alanmoo API responses already tie profile ids to headshot URLs, would there any privacy concerns over also having a dedicated "just the headshot" route?

**Comment by Pomax** [comment]
I'm also not entirely sure whether this is a thing we can easily do, if the API server itself just deals with the metadata. I'm sure we don't want the API server to also become an image proxy, so we'll have to think about how best to get images resized in a way that doesn't bog down the API server itself.

**Comment by patjouk** [comment]
We were discussing this issue with @cadecairos and it reminded me of that: https://github.com/codingjoe/django-stdimage. It sounds pretty cool and we could use this https://github.com/glemmaPaul/django-stdimage-serializer/blob/master/stdimage_serializer/fields.py as a prototype to build our own serializer.
Maybe that could unblock you?

**Comment by Pomax** [comment]
Oh wow, that definitely looks pretty cool, let's see how far that gets us!

**Comment by youriwims** [comment]
@Pomax am I able to just install and use the `StdImageField` or should I be waiting for the serializer to be built?
