### ISSUE TITLE
Add Entry "type" field

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#479]
Based on https://github.com/mozilla/network-pulse/issues/1030: add a new field called `entry_type` to the Entry model, and update the get/post routes for entries to check for that value in preparation of adding model serializers that "fit" each of the entry types defined in our [table of entry types](https://docs.google.com/document/d/1LITsvpTJaafsyGuVrNeE27Sz_XY1Ase2D8IWCmu7dLk/edit?ts=5cadf65b#heading=h.p4wvs4fhqwpl)

**Comment by gideonthomas** [comment]
@Pomax one other piece that would need to be done is how these entry types show up in the admin since the admin interface doesn't use our drf serializers. Probably should be a separate ticket?

**Comment by Pomax** [comment]
pretty sure that as a charfield with a choice list, it'll just show up as a string in the admin interface?

**Comment by Pomax** [comment]
![image](https://user-images.githubusercontent.com/177243/56612945-714a3a80-65ca-11e9-8009-bf43bdf4287b.png)

**Comment by Pomax** [comment]
![image](https://user-images.githubusercontent.com/177243/56612970-7909df00-65ca-11e9-88cc-b7abe51c3fc3.png)

**Comment by gideonthomas** [comment]
I would imagine that we don't want to show certain fields in the admin based on your choice of entry types? For e.g. I don't think we would want to show get involved or image for the session entry type in the admin? That might be a nice to have, but just thinking about other users of the admin who might be confused by which fields need to be filled out.

**Comment by Pomax** [comment]
Yeah that feels like a nice to have rather than a hard requirement: ideally the admin would switch what it shows "on the fly" simply by you picking a diffferent entry type, and that is "a lot of work(tm)" to make happen because now we're talking a full entry payload but JS hiding/revealing based on a python serializer... that gets really complex really fast.

**Comment by gideonthomas** [comment]
Ah, yeah I was thinking more of just a JS show/hide solution without worrying about the payload; at least that's how I did it before.

But yeah makes sense - def a nice to have.

**Comment by Pomax** [comment]
filed it to make sure we don't lose that thought, though!
