### ISSUE TITLE
Create basket signup endpoint

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#496]
The footer is going to have a signup form for the Mozilla newsletter, but we need an endpoint on the Pulse API that will accept it and submit to an SQS, like on the foundation site.

If you start working on this, unassign the other person.

**Comment by Pomax** [comment]
We can probably take the foundation's campaigns's `views.py` and hook that into the Pulse API - probably with less code because there's no petition vs. signup?

**Comment by cadecairos** [comment]
yeah, this should be pretty straight-forward if we use the code we already wrote.
