### ISSUE TITLE
Newsletter sign-up

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#506]
Related to Join Us Flow work https://github.com/mozilla/network-pulse/issues/1092
Full flow mockups can be found on [Redpen](https://redpen.io/p/wp17e9f94b044da4a0)

---

@gideonthomas 

On the screen below there's a checkbox for newsletter sign up. Do you know if Pulse API already has a way to handle this? And if so, how can Pulse front-end pass the boolean over to API.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/2896608/59136013-154b3380-8936-11e9-94d2-c490170df909.png">

**Comment by gideonthomas** [comment]
cc @Pomax for documentation.

**Comment by Pomax** [comment]
closing as stale
