### ISSUE TITLE
Update README's Social Auth section

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#508]
https://github.com/mozilla/network-pulse-api#setting-up-social-authentication

To add a new "Social Application" instance you also need to "choose a site"

![choose-a-site](https://user-images.githubusercontent.com/2896608/59314476-704c9580-8c6a-11e9-8a2d-91ef77ef1c9b.gif)

/cc @gideonthomas

**Comment by gideonthomas** [comment]
Fixed in https://github.com/mozilla/network-pulse-api/pull/509
