### ISSUE TITLE
Add "created" field to profile and user model

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#514]
Currently, we don't record a create date on new profiles or new users. This fall, we aim to onboard program applicants more diligently (e.g. awards, mozfest). Create date will help us track whether our work is effective or not. Let's add it.

**Comment by alanmoo** [comment]
If we have to put a date for existing profiles (or if, @Pomax, you think it makes more sense to give a default), let's go with January 26, 2016 (The date of the first Pulse commit).

**Comment by Pomax** [comment]
![image](https://user-images.githubusercontent.com/177243/60309427-8e6cf380-9902-11e9-9387-938517dee89a.png)

**Comment by xmatthewx** [comment]
Any blockers on this, or is it coming along okay?
