### ISSUE TITLE
Strip # symbol from tags on entry submission

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#524]
A few users have oddly used `#` on tags. This feels odd for comma separated tags that aren't in paragraph text. It could confuse users. For example `#mozfest`. It feels like a thing that could lead to trouble if not fixed. 

 - Proposed fix: silently strip the symbol when new entries are submitted. 
 - For existing tags in DB, we probably want to edit or merge (if its sibling exists).

Note: 
 - probably best to discuss current usage on MozFest site with Zannah. When ready to ship, be sure to update usage by mozfest website.  

cc @natalieworth @Pomax @alanmoo

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
