### ISSUE TITLE
Add Slackbot for posts with specific tag

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#553]
The fellowships team has asked to add a bot to #mofo_fellowships that posts new Pulse entries tagged with #mozfellows19.

I'm not sure if this needs RSS work or can be accomplished with the existing tools in Zapier.

**Comment by kristinashu** [comment]
cc @gideonthomas

**Comment by Pomax** [comment]
We heavily de-emphasized tags in favour of categories, should https://github.com/mozilla/network-pulse-api/pull/561 still be tapping into tags, or should it be tapping into categories instead?

**Comment by gideonthomas** [comment]
Done
