### ISSUE TITLE
Update to Django 2.2 LTS

### ISSUE THREAD

**Issue by patjouk** [mozilla/network-pulse-api#575]
Django 1.11 won't be receiving any security updates starting April 2020. We should schedule some time next year to migrate to 2.2 (LTS until 04.2022).

**Comment by Pomax** [comment]
- [ ] uplift to 2.2.11
- [ ] update url(...) to path(...) with [2.x style parameter capture](https://docs.djangoproject.com/en/3.0/releases/2.0/#simplified-url-routing-syntax) where possible
