### ISSUE TITLE
Skip "Grant Pulse API access to your account" step if user is not Mozilla Staff

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#59]
@Pomax @alanmoo Is it possible if we can skip the following screen if user is not logged in using a Mozilla Staff account?

<img width="680" alt="screen shot 2017-01-25 at 8 38 07 pm" src="https://cloud.githubusercontent.com/assets/2896608/22320143/66346b2c-e33e-11e6-82a9-b67d2059fa29.png">

Current flow:

1. user clicks on "sign in" on Pulse
2. user is redirected to Google's log in page
2. user logs into Google using a non Mozilla Staff account
3. user gets to the "Grant Pulse API access to your account" step
4. use clicks "Allow" to **grant access**
5. user gets redirected back to Pulse and sees **"Sign in failed. Only Mozilla staff can login now as we test this new platform. Check back soon!"** message

This flow could be quite confusing to people. Also, even though this user cannot log into Pulse he/she has already given Pulse API access to his/her Google account. (and he/she will have to go to https://myaccount.google.com/permissions to find this out)

<img width="742" alt="screen shot 2017-01-25 at 8 55 21 pm" src="https://cloud.githubusercontent.com/assets/2896608/22320366/b7302ef6-e340-11e6-8ffb-d1dcfb7dfa51.png">

/cc @Pomax @alanmoo @kristinashu

**Comment by Pomax** [comment]
There is not - we cannot control which pages google shows for its oauth permission granting process on their own domain.

**Comment by mmmavis** [comment]
Ah I see. If that's the case maybe we can refine the sign in error message so it's more descriptive? https://github.com/mozilla/network-pulse/issues/317 Let's move this conversation there.
