### ISSUE TITLE
We probably don't need `original_url` param for /login

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#60]
I think Google automatically remembers the URL you were at before coming to Google's log in page. I started from page `https://localhost:3000/add?test=hellomavis` and then I redirected myself to `https://localhost:8000/login` (no param) which then sent me to a `https://accounts.google.com/o/oauth2/auth` url with a bunch of params including one called `state`

```
state=http%3A%2F%2Flocalhost%3A3000%2Fadd%3Ftest%3Dhellomavis
```

Once I completed the auth flow I was successfully redirected back to `https://localhost:3000/add?test=hellomavis&loggedin=boolean`

/cc @Pomax @alanmoo

**Comment by mmmavis** [comment]
aha we DO need `original_url` 😂 😂 😂 

I realized I was passing in `window.location.toString()` as `original_url` somewhere deeper in the chain. That's why I was "magically" redirected back to where I was.

**Comment by Pomax** [comment]
yeah we *really* do =D

**Comment by alanmoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1682681/22377329/7291f032-e47f-11e6-9d50-2280090b74a9.png)
