### ISSUE TITLE
"type" as part of the /userstaus response

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#61]
@Pomax @alanmoo 

Currently response from a /userstatus call is either

**for Mozilla Staff**
```
{
  username: <string: the user's full name according to Google>,
  email: <string: the user's google-login-associated email address>
  loggedin: true
}
```

OR 

**for Non Mozilla Staff or user that hasn't gone through Google sign in/auth process**

```
{
  loggedin: false
}
```

On Pulse front end we need a way to distinguish Non Mozilla Staff from "unknown" person so we can display content accordingly

e.g., for **Non Mozilla Staff** we want to show "Only Mozilla staff can login now as we test this new platform. Check back soon!" vs for **"unknown" user** we want to prompt him/sher to sign in.

Is it possible if we can make the response of the /userstatus call more descriptive? I was thinking about adding `type` as part of the meta and `staff`, `nonstaff`, and `unknown` can be the 3 possible values.

**Comment by alanmoo** [comment]
I believe the current behavior effectively doesn't let a user log in if they're not staff, so we don't have the nonstaff/unknown differentiated. Is this something that's needed for launch?

**Comment by Pomax** [comment]
There should not be any distinction based on type for v2 as far as I remember from our. Everyone can view results, only people with a mozilla account can post. There is no distinction between "not having a mozilla account" and "not being a user" until v3.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
