### ISSUE TITLE
Oder by profile triggers an exception

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network-pulse-api#621]
I got paged due to a higher than normal number of 500 internal server errors on the pulse API. It looks like our DRF uplift missed something, because [this query will trigger an internal server error](https://pulse-api.mofostaging.net/api/pulse/v2/entries/?format=api&ordering=-published_by.profile&page=1)

I am on mobile and can't copy and paste the whole exception, so [here's a link to the Scalyr logs](https://app.scalyr.com/events?centered=true&continuationToken=d2PpH_vPTXoV9yXV7T5YGwAfdiDaotBR&endTime=1582775995359&highlightEvent=d2PpH_vPTXoV9yXV7T5YGwAfdiDaotBR&inclusiveStart=true&log=logplex&logSource=network-pulse-api-production&startTime=1582771794782&teamToken=XWtkK9T83J_RAFagZIxcew--&tokenCentered=true)

**Comment by Pomax** [comment]
fixed with latest deploy
