### ISSUE TITLE
Convert all existing images to images > 500kb 

### ISSUE THREAD

**Issue by patjouk** [mozilla/network-pulse-api#629]
Following of #628 

We want to automatically convert all existing images to images that are not killing my current data plan :D

It will require to:
- get the image linked to the entry/profile
- transform it to make it under the 500kb limit
- associate the new image to the entry/profile
- delete the previous one to keep S3 clean ✨

**Comment by cadecairos** [comment]
@patjouk as a stop-gap can you file a related issue to optimize the ~6 images that are far to large for their own good?

**Comment by patjouk** [comment]
It would be nice, but not sure it's ever gonna happen. Closing it for now.
