### ISSUE TITLE
turn off detailed error pages on production and staging

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network-pulse-api#63]
I'm not entirely sure how to set it, without digging through the docs, but we need to turn off debug error pages on the production and staging apps on heroku.

**Comment by alanmoo** [comment]
Gonna go ahead and guess this line will do it. https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/settings.py#L24-L25

**Comment by alanmoo** [comment]
Also [this](https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/#run-manage-py-check-deploy) is handy

**Comment by alanmoo** [comment]
@cadecairos this is in. Can we get this live tomorrow?

**Comment by cadecairos** [comment]
Yarp!
