### ISSUE TITLE
"inv setup" raises error

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#679]
`dropdb: could not connect to database template1: FATAL:  role "postgres" does not exist`

**Comment by Pomax** [comment]
This is caused by https://github.com/mozilla/network-pulse-api/blob/master/tasks.py#L101, which assumes the username `postgres` (which is the default pg username) still exists.

**Comment by mmmavis** [comment]
Problem solved. It was due to an issue on my end 😓 Sorry for the false alarm.
