### ISSUE TITLE
Fields shown at /entries endpoint

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#7]
Should we show the person who submitted a project in the entries response? Presumably we'll want to in the future, but to start all of them are just going to be a database migration so we'll have to have a default. If we do show it in the public response, I imagine we don't want to show email address; What do we expose for that field?

**Comment by Pomax** [comment]
yeah exposing email addresses is not a very good idea, but it feels like there is value in showing the poster's name for entries. I seem to recall the serializer being able to do that for us, but I might be remembering wrong.

@xmatthewx, thoughts?

**Comment by alanmoo** [comment]
We have the 'published by' user stored in the db but not exposed via the endpoint. We can change that in the future if we want, but since most of these will be by one person for now it's not very exciting.
