### ISSUE TITLE
Duplicated entries?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#71]
Not sure why but I started seeing duplicated entries on staging today. e.g., https://network-pulse-api-staging.herokuapp.com/entries/?ordering=-created&page_size=1000&search=mavis

**Comment by Pomax** [comment]
Did we rerun the migration without emptying the database @alanmoo?

**Comment by alanmoo** [comment]
Yes, as I wanted to make sure the migration would work onto production properly. Is this causing issues?

@pomax Is there an easy way to pull the heroku production db back into staging?

**Comment by alanmoo** [comment]
Scratch that, I logged into the admin and deleted older sets, so there shouldn't be duplicates now. If there are, @mmmavis you're an admin on the staging server so you can log in and check/manage the data directly

**Comment by mmmavis** [comment]
kk I just don't wanna break anything unintentionally. I'll check with you guys before I make any changes in the future.
