### ISSUE TITLE
API doesn't work without a .env file

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network-pulse-api#72]
I'm setting this up locally to do some testing, and I'm having some difficulty.

OS: Ubuntu 16.10
Python: 3.5

I ran:
1. `pip install -r requirements.txt`
2. `python manage.py migrate`
3. `python manage.py runserver`

What I end up seeing is this error in console:
`/home/cade/.Envs/pulse/lib/python3.5/site-packages/environ/environ.py:617: UserWarning: Error reading /home/cade/code/network-pulse-api/.env - if you're not configuring your environment separately, check this.`

And trying to load the admin tool results in a 400 response code.

**Comment by Pomax** [comment]
That's definitely bad, although I should also point out it looks like you forgot a `python manage.py makemigrations` between steps 1 and 2.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
