### ISSUE TITLE
Add SSL_PROTECTION=False to sample.env

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#75]
@alanmoo @Pomax 

Regardless of my browser config/history, http://test.example.com:8000/ always gets redirected to https:// and Pulse API on dev mode doesn't like it. 😨 

<img width="1106" alt="screen shot 2017-02-17 at 6 15 26 pm" src="https://cloud.githubusercontent.com/assets/2896608/23091650/c8aa2ff6-f56f-11e6-8233-48552682b341.png">

It seems like setting env var `SSL_PROTECTION` to `False` solves the problem. Can we please add that to `sample.env` as well as mention copying `sample.env` to `.env` in [README's Getting up and running for local development section](https://github.com/mozilla/network-pulse-api#getting-up-and-running-for-local-development)?

**Comment by mmmavis** [comment]
Update:

I started to having that https redirect problem since this commit https://github.com/mozilla/network-pulse-api/commit/0e8a9f00ceaea6414ccd59745a6a0ff0cea9db03 . Setting `SSL_PROTECTION=False` solved the problem. But when I checked out to `master` I hit the same problem even when `SSL_PROTECTION` is set to `False`.

**Comment by Pomax** [comment]
I think I found the problem: https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/settings.py defaults `SSL_PROTECTION` to `True`, which I'm pretty sure should be `False` because the vast majority of the work is done by devs, not by deployment machines. @alanmoo mind if we change that to *not* enabled by default?

**Comment by alanmoo** [comment]
Wfm. I guess I was thinking we didn't want to accidentally ship without ssl but this logic makes sense too
