### ISSUE TITLE
Wrong object format in README's POST /entries section

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#76]
@Pomax @alanmoo 

The object format mentioned in [POST /entries/ section on README](https://github.com/mozilla/network-pulse-api/#post-entries) doesn't seem to match what Pulse API actually accepts, instead of 

```
{
  csrfmiddlewaretoken: '<csrf token>'
  nonce: '<nonce value obtained from [GET /nonce]>',
  data: {
    title: ...
    ...
  }
}
```

Pulse API takes
```
{
  csrfmiddlewaretoken: '<csrf token>'
  nonce: '<nonce value obtained from [GET /nonce]>',
  title: ...
  ...
}
```
(no need to wrap properties of entry in a data object)

Not sure if we wanna keep the current accepted format and fix README or the other way around.

**Comment by Pomax** [comment]
That is very odd. Since fixing the readme is far easier, let's do that.

**Comment by Pomax** [comment]
vicksed
