### ISSUE TITLE
make signups moderated

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#779]
Allow signups to go through, but don't automatically mark new accounts as active. Instead, admins should flag accounts as active based on a knowledge of who the person behing the signup is.  That way we don't need to clamp down on signups as hard, and we can filter API resonses to only data associated with active user accounts.

- [x] allow signups, but leave new accounts "inactive"
- [ ] update the API routes for user and profile data to exclude inactive acccounts
- [ ] possibly update the API route for posts so that posts by deactivated users no longer show up?

**Comment by danielfmiranda** [comment]
Meeting scheduled with Pomax for 04/11/22 to pair through this ticket
