### ISSUE TITLE
Re-implement the user signup flow

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#795]
Once there is an actual plan to properly work on Pulse, user accounts should be created the "conventional" way, where someone signs up, then has to confirm their account using an activation link to their email account. Once signed up, the user's presence in API calls (getting users, profiles, etc) and submissions should be omitted until a moderator "okays" the account (i.e. all data should be filtered for `user__is_public=True`, using a new field in addition to the standard `is_active`).

This allows users to sign up, log in, create posts, set their profile, etc. while pending moderation, rather than having to wait for a moderator before they can even log in, but their data will not show up for anyone until a staff member goes "yes, this is a trustworthy account" and marks them as public.

**Comment by danielfmiranda** [comment]
Blocked by #792

**Comment by danielfmiranda** [comment]
Closing as this was taken care of by #798 and #801
