### ISSUE TITLE
Update UserProfile.is_active to match EmailUser.is_active  

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/network-pulse-api#798]
In an effort to simplify and avoid future confusion, we would like to implement #791 and #795 using the `profile.is_active` flag instead of the `EmailUser.is_active` flag.

Our reasoning being:

1.If we move to the profile flag instead of the emailUser flag, It would allow users to sign up for pulse, verify their email, and edit their profiles/entries immediately, instead of being greeted with the "Inactive Account" page that was introduced earlier to combat spam accounts.
2. We could then use the profile `is_active` flag to filter out posts of "unapproved" users as requested in #791
3. Once we have these posts hidden, we can close #795, as the sign up flow will be back to the original flow.

**Comment by cdanfon** [comment]
Hey @danielfmiranda Any updates on that pull request?
