### ISSUE TITLE
A few fields should not be required when posting new entries

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#80]
When posting an entry to Pulse API, by design  `csrfmiddlewaretoken`, `nonce`, `title`, and `content_url` should be the only 4 required fields. 

However, currently it seems like Pulse API sees

- `featured`
- `tags`
- `issues`
- `creators`

as required fields as well.  Posting without these 4 fields in the object I'm sending will result status `400` back.

**Comment by mmmavis** [comment]
Also, there's one property `user` that I'm not too sure what it is referring to in https://github.com/mozilla/network-pulse-api/blob/master/public/migrate.html#L125 .

**Comment by Pomax** [comment]
I think the `user` part there isn't actually being used...

**Comment by Pomax** [comment]
Hm, https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/entries/models.py#L40-L55 suggests tags, issues and creators can be empty....

**Comment by Pomax** [comment]
This works fine localhost, but not on the staging herokuapp. Investigation reveals that the staging app is in fact not calling `/nonce` so it's not surprising it's throwing 403, but we should verify this. I've filed https://github.com/mozilla/network-pulse/issues/386 on the client repo

**Comment by mmmavis** [comment]
from http://localhost:8080/migrate.html

<img width="863" alt="screen shot 2017-02-24 at 12 28 20 pm" src="https://cloud.githubusercontent.com/assets/2896608/23319800/ef6ee682-fa8c-11e6-8e30-4177ac7abee3.png">

All of them expect `array` as value. Maybe that's why?

**Comment by Pomax** [comment]
I can't reproduce this, which version of the api are you on and did you remember to migrate your database? (or remove it entirely and rebuilt it with a migrate command)

**Comment by mmmavis** [comment]
I did `git log` and the latest one shows

```bash
commit 5727053cd9d0a60c903373de210c794da8142b00
Author: Alan Mooiman <amooiman@gmail.com>
Date:   Wed Feb 22 15:11:22 2017 -0500

    CSRF_TRUSTED_ORIGINS env var (#88)
```

When I ran `python manage.py runserver` it didn't prompt me to migrate (I did run it a few days ago) . Should I nuke the db and test?

**Comment by mmmavis** [comment]
I did `git log` and the latest one shows

```bash
commit 5727053cd9d0a60c903373de210c794da8142b00
Author: Alan Mooiman <*****@****.com>
Date:   Wed Feb 22 15:11:22 2017 -0500

    CSRF_TRUSTED_ORIGINS env var (#88)
```

When I ran `python manage.py runserver` it didn't prompt me to migrate (I did run it a few days ago) . Should I nuke the db and test?

**Comment by Pomax** [comment]
it never prompts you to migrate. You have to do this yourself. Run the following:
```
$> python manage.py makemigrations
$> python manage.py migrate
```
If that throws errors, remove your db.sqlite3, then rerun `python manage.py migrate` (you'll then also have to rerun `python manage.py createsuperuser` to set up your first admin user)

**Comment by mmmavis** [comment]
> it never prompts you to migrate. You have to do this yourself. Run the following:

Sorry, bad choice of word, I shouldn't have said "prompt". I meant it didn't show a note to remind me to run migrate command. I can't recall what exactly the note reads. But I've definitely seen it before on occasion when migration was needed.

---

I just ran the 2 commands

```bash
(venv) mavisou:~/Development/network-pulse-api[master*]$ python manage.py makemigrations
No changes detected
(venv) mavisou:~/Development/network-pulse-api[master*]$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, creators, entries, issues, sessions, tags, users
Running migrations:
  No migrations to apply.
(venv) mavisou:~/Development/network-pulse-api[master*]$ 
```

**Comment by Pomax** [comment]
I don't remember ever seeing a message about a migration being necessary, but maybe I never noticed it. Just to be sure can you remove your db.sqlite3 and rebuild it?

**Comment by Pomax** [comment]
trying this as a direct POST rather than through the form fails with the same notice. http://stackoverflow.com/questions/40237969/django-foreignkey-field-required-despite-blank-true-and-null-true looks like it might help us
