### ISSUE TITLE
Support new users signing up

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/network-pulse-api#802]
This ticket is made to support new pulse users signing up to the application, as well as marking all of these users as "active" on the backend. 

Tasks:
---
- [ ] Reach out to Zannah to discuss what support is needed, as well as schedule a time to mark all of the new users who signed up as "active" so their profiles and posts will appear on the front end

**Comment by cdanfon** [comment]
We will close this issue for the time being, Anil to catch up with Marc in the future and open a new issue if needed.
