### ISSUE TITLE
Should a post be able to come with "featured" or should this be an admin-only thing

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#83]
Right now for convenience we allow entries to be posted with `featured: true` for migration purposes, but this is exceptionally questionable once we go live: should we look into making sure this value cannot be specific in post data, but instead can only be triggered through admin/its own REST endpoint?

(Especially if we intend to expand the userbase to a point where not every user is staff!)

/cc @mmmavis @alanmoo @xmatthewx

**Comment by mmmavis** [comment]
I would vote for having `featured` option available only on Django's admin dashboard.

**Comment by alanmoo** [comment]
Yeah, admin dashboard only makes sense to me.

**Comment by xmatthewx** [comment]
Good idea to block that.

Some day, it'd be awesome for admin staff to be able to feature things from the frontend. That day is _definitely_ not today. Cross that bridge when we get there?

**Comment by Pomax** [comment]
sounds like a uninamimous vote, filed as https://github.com/mozilla/network-pulse-api/issues/85
