### ISSUE TITLE
Improve Admin of Entries

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#90]
Admin for Entries currently shows the oldest project first. That's fine today, but will get tedious later. Can we default to reverse chronological? Also nice to have: add columns for date and published_by and offer sort on each?

https://pulse-api.mofoprod.net/admin/entries/entry/?all=

**Comment by xmatthewx** [comment]
Would also be nice to have basic search if django makes that easy.

**Comment by Pomax** [comment]
This should be relatively easy to add to the admin view, http://djangobook.com/customizing-change-lists-forms/ covers this topic specifically so we should just be able to follow the "recipe"

**Comment by xmatthewx** [comment]
View entries by tag would be another very useful admin feature (let me know if I should open a new issue).

Use case: Kevin wants to feature Games on the network site, wants to correct a few tags and typos he sees on several projects. Workflow: Admin > Tags > Games > List of related entries with link to edit.

**Comment by Pomax** [comment]
@gideonthomas for a consultation on how much effort is involved in setting that up

**Comment by gideonthomas** [comment]
> Can we default to reverse chronological?
single line change

> add columns for date and published_by and offer sort on each
is this when you look at the list of entries? or is this for each entry? If this is for the list of entries, and these fields already exist, they are 2-3 line changes

> Would also be nice to have basic search if django makes that easy.
single line change

> View entries by tag would be another very useful admin feature
Easy if you are ok with the crappy UX if you use default filtering for tags in django (it'll be a very long list). Otherwise, it's a bit of work to show list of related entries for a tag.

**Comment by xmatthewx** [comment]
All of these would be for browsing lists of entries, not changes to edit view of a single entry. Easy crappy UX is probably good enough for now. We can improve further later if & when we find a big need. 

I saw that Alan added ability to browse authors and see a list of their entries, though list doesn't link to entry edit view. So this would be hard to build for tag admin view? Just asking to clarify. We can pursue simpler filtering.

**Comment by Pomax** [comment]
This will land as part of https://github.com/mozilla/network-api/pull/215/files#diff-fa9914df4bee61edc71be2c2a2b691ef, with the migration of pulse-api into network-api

**Comment by Pomax** [comment]
This PR landed, adding:

- `moderation_state` on the Entry model
- four predefined ModerationState instances: "Pending", "In Review", "Approved" and "Declined"
- `api/pulse/entries/moderation-states` endpoint for getting the list of available moderation states
- `api/pulse/entries/<entryid>/moderate/<stateid>` endpoint for changing the moderation state of an entry, provided the user has "entry change" permissions.
- `api/pulse/entries` now returns either "all approved" for normal users, or if the user is logged in with "change entry" permissions (e.g. moderators and superusers) they will get "all entries" back instead.

**Comment by xmatthewx** [comment]
💥 !!
