### ISSUE TITLE
Update doc for /entries/<id=number>/bookmark

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#92]
https://github.com/mozilla/network-pulse-api#put-entriesidnumberbookmark

It seems like a payload object is needed

```
{
  csrfmiddlewaretoken: required csrf token string obtained from [GET /nonce]
  nonce: required nonce string obtained from [GET /nonce]
}
``` 

and `X-CSRFToken` request header has to be set.

**Comment by Pomax** [comment]
good point, PUT basically needs the same data as POST. I'll update that tomorrow
