### ISSUE TITLE
Split bookmark and unbookmark routes

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#94]
Currently `/entries/<id=number>/bookmark` route toggles an entry's bookmark state. I'm wondering if we should split it into 2 different routes - one for bookmark and one for unbookmark.

On Pulse frontend site, for users who are not logged in we are storing bookmarked' entry ids in`localStorage`. Once they are logged in we want the UI (heart icon) to also reflect each entry's bookmarked stated that's stored with their account.

**I was thinking about this scenario -**

(note I'm planning to have 2 arrays in `localStorage` - `bookmarkedIds` and `unbookmarkedIds`)

A user bookmarked entry number `28` before he/she was logged in. We stored `28` in `localStorge.bookmarkedIds` and filled heart icon UI of entry `28` to represent its bookmarked state. Now this user decides to log in. In the database entry `28` was already bookmarked with this user at an earlier time. After user is logged in, Pulse sees `28` stored in `localStorge.bookmarkedIds` and it tries to call `/entries/28/bookmark` to change the bookmarked state of `28` in the database to `true`. However, since `/entries/<id=number>/bookmark` toggles a bookmark state, entry `28` is now unbookmakred by the user, which is the opposite of what user intended to do.

I guess Pulse *could* make a `GET /entries/<id=number>/` call to find out the current bookmarked state in the database first before making the `PUT /entries/<id=number>/bookmark` call. But this would double up the API calls we are making.

Thoughts? @pomax @alanmoo

**Comment by alanmoo** [comment]
You can access `/entries/bookmarks/` to see which entries are already server-bookmarked and then generate a list of which ones you need to server-bookmark based on that. But I can also see the benefit of making it a different route. I feel like @pomax and I discussed this briefly at some point and he had a reason why this was good.

**Comment by alanmoo** [comment]
Oh, [here we go](https://github.com/mozilla/network-pulse-api/pull/14#pullrequestreview-17704403). So basically we don't necessarily want to change this behavior but add another route to bookmark a whole bunch at once (and thus dramatically reducing amount of calls needed)

**Comment by mmmavis** [comment]
Created a ticket for adding a route to bookmark a list of entries: https://github.com/mozilla/network-pulse-api/issues/118. Closing this ticket now.
