### ISSUE TITLE
Redirect login to /admin

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#95]
Django login occurs at https://pulse-api.mofoprod.net. Users then need to manually point to https://pulse-api.mofoprod.net/admin

Can we make this better? Auto redirect? Include a link?

**Comment by Pomax** [comment]
a redirect makes sense, where logging in just takes you to the /admin view

**Comment by Pomax** [comment]
fixed - https://api.mozillapulse.org now gives a direct link to the admin interface or logout if you're already logged in, and redirects on login to the admin panel

**Comment by xmatthewx** [comment]
yay
