### ISSUE TITLE
Django & CMS on mobile

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#97]
As we explore django and cms options, we should keep mobile in mind. I wouldn't call it a critical requirement, but it's more than a trivial consideration. Django out of the box is not responsive, and super tiny on mobile. 

There is probably a better repo or spreadsheet for this comment. Maybe it's already been considered. 

@kristinashu can you triage this and close this issue?

**Comment by kristinashu** [comment]
Added it to the requirement spreadsheet https://docs.google.com/a/mozilla.com/spreadsheets/d/1mftbSX4P8sWQlS1_IOAdaU-7sFddrpy5vzp-CXEovF0/edit?usp=sharing
