### ISSUE TITLE
add image support, aligned with network-api

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#98]
implementation ticket filed associated with https://github.com/mozilla/network-pulse/issues/363

Based on the work by @cadecairos and @gideonthomas in https://github.com/mozilla/network-api/commit/d692ad329ab95d36028d3d7ebb122fbe9505d83b let's use their solution for image hosting in entries  for the network-pulse-api. As long as we don't insist on users being able to submit images-or-image-urls, but only images, this should be doable reasonably fast.

**Comment by Pomax** [comment]
Some questions:
- a PR is open at the moment that adds a `thumbnail` image field, but leaves the `thumbnail URL` field - both yield URLs when queries through the REST API, but having both seems better than having only one, in case we have content for which there is already a perfect image on the internet.
- The client will need a UI update to allow image data to be passed along with an entry. We're using the same code on the API side as the `network-api` project, so we should be able to look at the client code in `network` to see an example of the data format required for this field. It also feels like it makes sense to have the client present the thumbnail field in a way that lets the user pick one or the other, but not leave both empty, or both used.
- We'll need to hook up the correct S3 bucket values for our staging/production instance
- I noticed that removing images associated with entries does *not* delete the image. As such, we might end up with orphaned data in our bucket and I don't know of a way to make sure we clean up after ourselves (especially for images that should never accidentally make it onto the internet). @cadecairos, @gideonthomas did you look into this?

/cc @wex @xmatthewx

**Comment by xmatthewx** [comment]
Thanks for the update. Much of this sounds good.

> have the client present the thumbnail field in a way that lets the user pick one or the other, but not leave both empty, or both used

We _could_ leave the legacy field in the backend for now if migrating images or updating their URLs is tricky. I thought @alanmoo put these on S3 already. Could we migrate? If not, can we label the input `legacy plz dont use this`

I think doing both introduces complexity for us now and encourages hotlinking that will lead to broken images later. Let's just give users one way to do a thing. It'll be the expected experience.

**Comment by Pomax** [comment]
We can absolutely do that - we can keep it blank for new entries and not "human editable", and then we'll probably have to write a small migration script that ensures that the thumbnail_url data for current database entries are copied over to the new image field (which if I understand correctly, is encoded as a url in the database, too, so that might even be a single copy call)

**Comment by xmatthewx** [comment]
Closing. Tracking the frontend in #424 and the API https://github.com/mozilla/network-pulse-api/issues/98

**Comment by xmatthewx** [comment]
Is there where we're tracking the migration of images and deprecation of previous field? Any luck with that on staging yesterday?

**Comment by Pomax** [comment]
there isn't - it's such a one-off job we're not going with a documented step. Staging has been updated and all the entries that had a thumbnail before on https://network-pulse-staging.herokuapp.com now have a "normal" thumbnail property pointing to a working image.

**Comment by Pomax** [comment]
apparently we never closed this issue, but this totally happened already =D
